// Code generated by ent, DO NOT EDIT.

package claimevidence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the claimevidence type in the database.
	Label = "claim_evidence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClaimID holds the string denoting the claim_id field in the database.
	FieldClaimID = "claim_id"
	// FieldEvidenceID holds the string denoting the evidence_id field in the database.
	FieldEvidenceID = "evidence_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeClaim holds the string denoting the claim edge name in mutations.
	EdgeClaim = "claim"
	// EdgeEvidence holds the string denoting the evidence edge name in mutations.
	EdgeEvidence = "evidence"
	// Table holds the table name of the claimevidence in the database.
	Table = "claim_evidences"
	// ClaimTable is the table that holds the claim relation/edge.
	ClaimTable = "claim_evidences"
	// ClaimInverseTable is the table name for the Claim entity.
	// It exists in this package in order to avoid circular dependency with the "claim" package.
	ClaimInverseTable = "claims"
	// ClaimColumn is the table column denoting the claim relation/edge.
	ClaimColumn = "claim_id"
	// EvidenceTable is the table that holds the evidence relation/edge.
	EvidenceTable = "claim_evidences"
	// EvidenceInverseTable is the table name for the Evidence entity.
	// It exists in this package in order to avoid circular dependency with the "evidence" package.
	EvidenceInverseTable = "evidences"
	// EvidenceColumn is the table column denoting the evidence relation/edge.
	EvidenceColumn = "evidence_id"
)

// Columns holds all SQL columns for claimevidence fields.
var Columns = []string{
	FieldID,
	FieldClaimID,
	FieldEvidenceID,
	FieldType,
	FieldNote,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ClaimEvidence queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClaimID orders the results by the claim_id field.
func ByClaimID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimID, opts...).ToFunc()
}

// ByEvidenceID orders the results by the evidence_id field.
func ByEvidenceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvidenceID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByClaimField orders the results by claim field.
func ByClaimField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClaimStep(), sql.OrderByField(field, opts...))
	}
}

// ByEvidenceField orders the results by evidence field.
func ByEvidenceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEvidenceStep(), sql.OrderByField(field, opts...))
	}
}
func newClaimStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClaimInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ClaimTable, ClaimColumn),
	)
}
func newEvidenceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EvidenceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, EvidenceTable, EvidenceColumn),
	)
}
