// Code generated by ent, DO NOT EDIT.

package claimevidence

import (
	"api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLTE(FieldID, id))
}

// ClaimID applies equality check predicate on the "claim_id" field. It's identical to ClaimIDEQ.
func ClaimID(v uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldClaimID, v))
}

// EvidenceID applies equality check predicate on the "evidence_id" field. It's identical to EvidenceIDEQ.
func EvidenceID(v uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldEvidenceID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldType, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldCreatedAt, v))
}

// ClaimIDEQ applies the EQ predicate on the "claim_id" field.
func ClaimIDEQ(v uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldClaimID, v))
}

// ClaimIDNEQ applies the NEQ predicate on the "claim_id" field.
func ClaimIDNEQ(v uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNEQ(FieldClaimID, v))
}

// ClaimIDIn applies the In predicate on the "claim_id" field.
func ClaimIDIn(vs ...uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldIn(FieldClaimID, vs...))
}

// ClaimIDNotIn applies the NotIn predicate on the "claim_id" field.
func ClaimIDNotIn(vs ...uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNotIn(FieldClaimID, vs...))
}

// EvidenceIDEQ applies the EQ predicate on the "evidence_id" field.
func EvidenceIDEQ(v uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldEvidenceID, v))
}

// EvidenceIDNEQ applies the NEQ predicate on the "evidence_id" field.
func EvidenceIDNEQ(v uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNEQ(FieldEvidenceID, v))
}

// EvidenceIDIn applies the In predicate on the "evidence_id" field.
func EvidenceIDIn(vs ...uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldIn(FieldEvidenceID, vs...))
}

// EvidenceIDNotIn applies the NotIn predicate on the "evidence_id" field.
func EvidenceIDNotIn(vs ...uuid.UUID) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNotIn(FieldEvidenceID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldContainsFold(FieldType, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.FieldLTE(FieldCreatedAt, v))
}

// HasClaim applies the HasEdge predicate on the "claim" edge.
func HasClaim() predicate.ClaimEvidence {
	return predicate.ClaimEvidence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ClaimTable, ClaimColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClaimWith applies the HasEdge predicate on the "claim" edge with a given conditions (other predicates).
func HasClaimWith(preds ...predicate.Claim) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(func(s *sql.Selector) {
		step := newClaimStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvidence applies the HasEdge predicate on the "evidence" edge.
func HasEvidence() predicate.ClaimEvidence {
	return predicate.ClaimEvidence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, EvidenceTable, EvidenceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEvidenceWith applies the HasEdge predicate on the "evidence" edge with a given conditions (other predicates).
func HasEvidenceWith(preds ...predicate.Evidence) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(func(s *sql.Selector) {
		step := newEvidenceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClaimEvidence) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClaimEvidence) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClaimEvidence) predicate.ClaimEvidence {
	return predicate.ClaimEvidence(sql.NotPredicates(p))
}
