// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Claim is the predicate function for claim builders.
type Claim func(*sql.Selector)

// ClaimEvidence is the predicate function for claimevidence builders.
type ClaimEvidence func(*sql.Selector)

// Evidence is the predicate function for evidence builders.
type Evidence func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)
