// Code generated by ent, DO NOT EDIT.

package claim

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the claim type in the database.
	Label = "claim"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeEvidences holds the string denoting the evidences edge name in mutations.
	EdgeEvidences = "evidences"
	// EdgeClaimEvidences holds the string denoting the claim_evidences edge name in mutations.
	EdgeClaimEvidences = "claim_evidences"
	// Table holds the table name of the claim in the database.
	Table = "claims"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "claims"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// EvidencesTable is the table that holds the evidences relation/edge. The primary key declared below.
	EvidencesTable = "claim_evidences"
	// EvidencesInverseTable is the table name for the Evidence entity.
	// It exists in this package in order to avoid circular dependency with the "evidence" package.
	EvidencesInverseTable = "evidences"
	// ClaimEvidencesTable is the table that holds the claim_evidences relation/edge.
	ClaimEvidencesTable = "claim_evidences"
	// ClaimEvidencesInverseTable is the table name for the ClaimEvidence entity.
	// It exists in this package in order to avoid circular dependency with the "claimevidence" package.
	ClaimEvidencesInverseTable = "claim_evidences"
	// ClaimEvidencesColumn is the table column denoting the claim_evidences relation/edge.
	ClaimEvidencesColumn = "claim_id"
)

// Columns holds all SQL columns for claim fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldTitle,
	FieldBody,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// EvidencesPrimaryKey and EvidencesColumn2 are the table columns denoting the
	// primary key for the evidences relation (M2M).
	EvidencesPrimaryKey = []string{"claim_id", "evidence_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Claim queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByEvidencesCount orders the results by evidences count.
func ByEvidencesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEvidencesStep(), opts...)
	}
}

// ByEvidences orders the results by evidences terms.
func ByEvidences(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEvidencesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByClaimEvidencesCount orders the results by claim_evidences count.
func ByClaimEvidencesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClaimEvidencesStep(), opts...)
	}
}

// ByClaimEvidences orders the results by claim_evidences terms.
func ByClaimEvidences(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClaimEvidencesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newEvidencesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EvidencesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, EvidencesTable, EvidencesPrimaryKey...),
	)
}
func newClaimEvidencesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClaimEvidencesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ClaimEvidencesTable, ClaimEvidencesColumn),
	)
}
