// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/project"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Claim is the model entity for the Claim schema.
type Claim struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Body holds the value of the "body" field.
	Body *string `json:"body,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClaimQuery when eager-loading is set.
	Edges        ClaimEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClaimEdges holds the relations/edges for other nodes in the graph.
type ClaimEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Evidences holds the value of the evidences edge.
	Evidences []*Evidence `json:"evidences,omitempty"`
	// ClaimEvidences holds the value of the claim_evidences edge.
	ClaimEvidences []*ClaimEvidence `json:"claim_evidences,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClaimEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// EvidencesOrErr returns the Evidences value or an error if the edge
// was not loaded in eager-loading.
func (e ClaimEdges) EvidencesOrErr() ([]*Evidence, error) {
	if e.loadedTypes[1] {
		return e.Evidences, nil
	}
	return nil, &NotLoadedError{edge: "evidences"}
}

// ClaimEvidencesOrErr returns the ClaimEvidences value or an error if the edge
// was not loaded in eager-loading.
func (e ClaimEdges) ClaimEvidencesOrErr() ([]*ClaimEvidence, error) {
	if e.loadedTypes[2] {
		return e.ClaimEvidences, nil
	}
	return nil, &NotLoadedError{edge: "claim_evidences"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Claim) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case claim.FieldTitle, claim.FieldBody, claim.FieldStatus:
			values[i] = new(sql.NullString)
		case claim.FieldCreatedAt, claim.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case claim.FieldID, claim.FieldProjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Claim fields.
func (_m *Claim) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case claim.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case claim.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case claim.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case claim.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = new(string)
				*_m.Body = value.String
			}
		case claim.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case claim.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case claim.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Claim.
// This includes values selected through modifiers, order, etc.
func (_m *Claim) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Claim entity.
func (_m *Claim) QueryProject() *ProjectQuery {
	return NewClaimClient(_m.config).QueryProject(_m)
}

// QueryEvidences queries the "evidences" edge of the Claim entity.
func (_m *Claim) QueryEvidences() *EvidenceQuery {
	return NewClaimClient(_m.config).QueryEvidences(_m)
}

// QueryClaimEvidences queries the "claim_evidences" edge of the Claim entity.
func (_m *Claim) QueryClaimEvidences() *ClaimEvidenceQuery {
	return NewClaimClient(_m.config).QueryClaimEvidences(_m)
}

// Update returns a builder for updating this Claim.
// Note that you need to call Claim.Unwrap() before calling this method if this Claim
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Claim) Update() *ClaimUpdateOne {
	return NewClaimClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Claim entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Claim) Unwrap() *Claim {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Claim is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Claim) String() string {
	var builder strings.Builder
	builder.WriteString("Claim(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Body; v != nil {
		builder.WriteString("body=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Claims is a parsable slice of Claim.
type Claims []*Claim
