// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"api/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ClaimEvidenceUpdate is the builder for updating ClaimEvidence entities.
type ClaimEvidenceUpdate struct {
	config
	hooks    []Hook
	mutation *ClaimEvidenceMutation
}

// Where appends a list predicates to the ClaimEvidenceUpdate builder.
func (_u *ClaimEvidenceUpdate) Where(ps ...predicate.ClaimEvidence) *ClaimEvidenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClaimID sets the "claim_id" field.
func (_u *ClaimEvidenceUpdate) SetClaimID(v uuid.UUID) *ClaimEvidenceUpdate {
	_u.mutation.SetClaimID(v)
	return _u
}

// SetNillableClaimID sets the "claim_id" field if the given value is not nil.
func (_u *ClaimEvidenceUpdate) SetNillableClaimID(v *uuid.UUID) *ClaimEvidenceUpdate {
	if v != nil {
		_u.SetClaimID(*v)
	}
	return _u
}

// SetEvidenceID sets the "evidence_id" field.
func (_u *ClaimEvidenceUpdate) SetEvidenceID(v uuid.UUID) *ClaimEvidenceUpdate {
	_u.mutation.SetEvidenceID(v)
	return _u
}

// SetNillableEvidenceID sets the "evidence_id" field if the given value is not nil.
func (_u *ClaimEvidenceUpdate) SetNillableEvidenceID(v *uuid.UUID) *ClaimEvidenceUpdate {
	if v != nil {
		_u.SetEvidenceID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ClaimEvidenceUpdate) SetType(v string) *ClaimEvidenceUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ClaimEvidenceUpdate) SetNillableType(v *string) *ClaimEvidenceUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ClaimEvidenceUpdate) SetNote(v string) *ClaimEvidenceUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ClaimEvidenceUpdate) SetNillableNote(v *string) *ClaimEvidenceUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ClaimEvidenceUpdate) ClearNote() *ClaimEvidenceUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetClaim sets the "claim" edge to the Claim entity.
func (_u *ClaimEvidenceUpdate) SetClaim(v *Claim) *ClaimEvidenceUpdate {
	return _u.SetClaimID(v.ID)
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_u *ClaimEvidenceUpdate) SetEvidence(v *Evidence) *ClaimEvidenceUpdate {
	return _u.SetEvidenceID(v.ID)
}

// Mutation returns the ClaimEvidenceMutation object of the builder.
func (_u *ClaimEvidenceUpdate) Mutation() *ClaimEvidenceMutation {
	return _u.mutation
}

// ClearClaim clears the "claim" edge to the Claim entity.
func (_u *ClaimEvidenceUpdate) ClearClaim() *ClaimEvidenceUpdate {
	_u.mutation.ClearClaim()
	return _u
}

// ClearEvidence clears the "evidence" edge to the Evidence entity.
func (_u *ClaimEvidenceUpdate) ClearEvidence() *ClaimEvidenceUpdate {
	_u.mutation.ClearEvidence()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClaimEvidenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClaimEvidenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClaimEvidenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClaimEvidenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClaimEvidenceUpdate) check() error {
	if _u.mutation.ClaimCleared() && len(_u.mutation.ClaimIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClaimEvidence.claim"`)
	}
	if _u.mutation.EvidenceCleared() && len(_u.mutation.EvidenceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClaimEvidence.evidence"`)
	}
	return nil
}

func (_u *ClaimEvidenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(claimevidence.Table, claimevidence.Columns, sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(claimevidence.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(claimevidence.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(claimevidence.FieldNote, field.TypeString)
	}
	if _u.mutation.ClaimCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.ClaimTable,
			Columns: []string{claimevidence.ClaimColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.ClaimTable,
			Columns: []string{claimevidence.ClaimColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.EvidenceTable,
			Columns: []string{claimevidence.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.EvidenceTable,
			Columns: []string{claimevidence.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claimevidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClaimEvidenceUpdateOne is the builder for updating a single ClaimEvidence entity.
type ClaimEvidenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClaimEvidenceMutation
}

// SetClaimID sets the "claim_id" field.
func (_u *ClaimEvidenceUpdateOne) SetClaimID(v uuid.UUID) *ClaimEvidenceUpdateOne {
	_u.mutation.SetClaimID(v)
	return _u
}

// SetNillableClaimID sets the "claim_id" field if the given value is not nil.
func (_u *ClaimEvidenceUpdateOne) SetNillableClaimID(v *uuid.UUID) *ClaimEvidenceUpdateOne {
	if v != nil {
		_u.SetClaimID(*v)
	}
	return _u
}

// SetEvidenceID sets the "evidence_id" field.
func (_u *ClaimEvidenceUpdateOne) SetEvidenceID(v uuid.UUID) *ClaimEvidenceUpdateOne {
	_u.mutation.SetEvidenceID(v)
	return _u
}

// SetNillableEvidenceID sets the "evidence_id" field if the given value is not nil.
func (_u *ClaimEvidenceUpdateOne) SetNillableEvidenceID(v *uuid.UUID) *ClaimEvidenceUpdateOne {
	if v != nil {
		_u.SetEvidenceID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ClaimEvidenceUpdateOne) SetType(v string) *ClaimEvidenceUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ClaimEvidenceUpdateOne) SetNillableType(v *string) *ClaimEvidenceUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ClaimEvidenceUpdateOne) SetNote(v string) *ClaimEvidenceUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ClaimEvidenceUpdateOne) SetNillableNote(v *string) *ClaimEvidenceUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ClaimEvidenceUpdateOne) ClearNote() *ClaimEvidenceUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetClaim sets the "claim" edge to the Claim entity.
func (_u *ClaimEvidenceUpdateOne) SetClaim(v *Claim) *ClaimEvidenceUpdateOne {
	return _u.SetClaimID(v.ID)
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_u *ClaimEvidenceUpdateOne) SetEvidence(v *Evidence) *ClaimEvidenceUpdateOne {
	return _u.SetEvidenceID(v.ID)
}

// Mutation returns the ClaimEvidenceMutation object of the builder.
func (_u *ClaimEvidenceUpdateOne) Mutation() *ClaimEvidenceMutation {
	return _u.mutation
}

// ClearClaim clears the "claim" edge to the Claim entity.
func (_u *ClaimEvidenceUpdateOne) ClearClaim() *ClaimEvidenceUpdateOne {
	_u.mutation.ClearClaim()
	return _u
}

// ClearEvidence clears the "evidence" edge to the Evidence entity.
func (_u *ClaimEvidenceUpdateOne) ClearEvidence() *ClaimEvidenceUpdateOne {
	_u.mutation.ClearEvidence()
	return _u
}

// Where appends a list predicates to the ClaimEvidenceUpdate builder.
func (_u *ClaimEvidenceUpdateOne) Where(ps ...predicate.ClaimEvidence) *ClaimEvidenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClaimEvidenceUpdateOne) Select(field string, fields ...string) *ClaimEvidenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClaimEvidence entity.
func (_u *ClaimEvidenceUpdateOne) Save(ctx context.Context) (*ClaimEvidence, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClaimEvidenceUpdateOne) SaveX(ctx context.Context) *ClaimEvidence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClaimEvidenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClaimEvidenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClaimEvidenceUpdateOne) check() error {
	if _u.mutation.ClaimCleared() && len(_u.mutation.ClaimIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClaimEvidence.claim"`)
	}
	if _u.mutation.EvidenceCleared() && len(_u.mutation.EvidenceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClaimEvidence.evidence"`)
	}
	return nil
}

func (_u *ClaimEvidenceUpdateOne) sqlSave(ctx context.Context) (_node *ClaimEvidence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(claimevidence.Table, claimevidence.Columns, sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClaimEvidence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, claimevidence.FieldID)
		for _, f := range fields {
			if !claimevidence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != claimevidence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(claimevidence.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(claimevidence.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(claimevidence.FieldNote, field.TypeString)
	}
	if _u.mutation.ClaimCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.ClaimTable,
			Columns: []string{claimevidence.ClaimColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.ClaimTable,
			Columns: []string{claimevidence.ClaimColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.EvidenceTable,
			Columns: []string{claimevidence.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.EvidenceTable,
			Columns: []string{claimevidence.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClaimEvidence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claimevidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
