// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ClaimEvidence is the model entity for the ClaimEvidence schema.
type ClaimEvidence struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ClaimID holds the value of the "claim_id" field.
	ClaimID uuid.UUID `json:"claim_id,omitempty"`
	// EvidenceID holds the value of the "evidence_id" field.
	EvidenceID uuid.UUID `json:"evidence_id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClaimEvidenceQuery when eager-loading is set.
	Edges        ClaimEvidenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClaimEvidenceEdges holds the relations/edges for other nodes in the graph.
type ClaimEvidenceEdges struct {
	// Claim holds the value of the claim edge.
	Claim *Claim `json:"claim,omitempty"`
	// Evidence holds the value of the evidence edge.
	Evidence *Evidence `json:"evidence,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ClaimOrErr returns the Claim value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClaimEvidenceEdges) ClaimOrErr() (*Claim, error) {
	if e.Claim != nil {
		return e.Claim, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: claim.Label}
	}
	return nil, &NotLoadedError{edge: "claim"}
}

// EvidenceOrErr returns the Evidence value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClaimEvidenceEdges) EvidenceOrErr() (*Evidence, error) {
	if e.Evidence != nil {
		return e.Evidence, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: evidence.Label}
	}
	return nil, &NotLoadedError{edge: "evidence"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClaimEvidence) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case claimevidence.FieldType, claimevidence.FieldNote:
			values[i] = new(sql.NullString)
		case claimevidence.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case claimevidence.FieldID, claimevidence.FieldClaimID, claimevidence.FieldEvidenceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClaimEvidence fields.
func (_m *ClaimEvidence) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case claimevidence.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case claimevidence.FieldClaimID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field claim_id", values[i])
			} else if value != nil {
				_m.ClaimID = *value
			}
		case claimevidence.FieldEvidenceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field evidence_id", values[i])
			} else if value != nil {
				_m.EvidenceID = *value
			}
		case claimevidence.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case claimevidence.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case claimevidence.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClaimEvidence.
// This includes values selected through modifiers, order, etc.
func (_m *ClaimEvidence) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClaim queries the "claim" edge of the ClaimEvidence entity.
func (_m *ClaimEvidence) QueryClaim() *ClaimQuery {
	return NewClaimEvidenceClient(_m.config).QueryClaim(_m)
}

// QueryEvidence queries the "evidence" edge of the ClaimEvidence entity.
func (_m *ClaimEvidence) QueryEvidence() *EvidenceQuery {
	return NewClaimEvidenceClient(_m.config).QueryEvidence(_m)
}

// Update returns a builder for updating this ClaimEvidence.
// Note that you need to call ClaimEvidence.Unwrap() before calling this method if this ClaimEvidence
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ClaimEvidence) Update() *ClaimEvidenceUpdateOne {
	return NewClaimEvidenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ClaimEvidence entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ClaimEvidence) Unwrap() *ClaimEvidence {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClaimEvidence is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ClaimEvidence) String() string {
	var builder strings.Builder
	builder.WriteString("ClaimEvidence(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("claim_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClaimID))
	builder.WriteString(", ")
	builder.WriteString("evidence_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EvidenceID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ClaimEvidences is a parsable slice of ClaimEvidence.
type ClaimEvidences []*ClaimEvidence
