// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ClaimEvidenceCreate is the builder for creating a ClaimEvidence entity.
type ClaimEvidenceCreate struct {
	config
	mutation *ClaimEvidenceMutation
	hooks    []Hook
}

// SetClaimID sets the "claim_id" field.
func (_c *ClaimEvidenceCreate) SetClaimID(v uuid.UUID) *ClaimEvidenceCreate {
	_c.mutation.SetClaimID(v)
	return _c
}

// SetEvidenceID sets the "evidence_id" field.
func (_c *ClaimEvidenceCreate) SetEvidenceID(v uuid.UUID) *ClaimEvidenceCreate {
	_c.mutation.SetEvidenceID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ClaimEvidenceCreate) SetType(v string) *ClaimEvidenceCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *ClaimEvidenceCreate) SetNote(v string) *ClaimEvidenceCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ClaimEvidenceCreate) SetNillableNote(v *string) *ClaimEvidenceCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ClaimEvidenceCreate) SetCreatedAt(v time.Time) *ClaimEvidenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ClaimEvidenceCreate) SetNillableCreatedAt(v *time.Time) *ClaimEvidenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ClaimEvidenceCreate) SetID(v uuid.UUID) *ClaimEvidenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ClaimEvidenceCreate) SetNillableID(v *uuid.UUID) *ClaimEvidenceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetClaim sets the "claim" edge to the Claim entity.
func (_c *ClaimEvidenceCreate) SetClaim(v *Claim) *ClaimEvidenceCreate {
	return _c.SetClaimID(v.ID)
}

// SetEvidence sets the "evidence" edge to the Evidence entity.
func (_c *ClaimEvidenceCreate) SetEvidence(v *Evidence) *ClaimEvidenceCreate {
	return _c.SetEvidenceID(v.ID)
}

// Mutation returns the ClaimEvidenceMutation object of the builder.
func (_c *ClaimEvidenceCreate) Mutation() *ClaimEvidenceMutation {
	return _c.mutation
}

// Save creates the ClaimEvidence in the database.
func (_c *ClaimEvidenceCreate) Save(ctx context.Context) (*ClaimEvidence, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClaimEvidenceCreate) SaveX(ctx context.Context) *ClaimEvidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClaimEvidenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClaimEvidenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClaimEvidenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := claimevidence.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := claimevidence.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClaimEvidenceCreate) check() error {
	if _, ok := _c.mutation.ClaimID(); !ok {
		return &ValidationError{Name: "claim_id", err: errors.New(`ent: missing required field "ClaimEvidence.claim_id"`)}
	}
	if _, ok := _c.mutation.EvidenceID(); !ok {
		return &ValidationError{Name: "evidence_id", err: errors.New(`ent: missing required field "ClaimEvidence.evidence_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ClaimEvidence.type"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ClaimEvidence.created_at"`)}
	}
	if len(_c.mutation.ClaimIDs()) == 0 {
		return &ValidationError{Name: "claim", err: errors.New(`ent: missing required edge "ClaimEvidence.claim"`)}
	}
	if len(_c.mutation.EvidenceIDs()) == 0 {
		return &ValidationError{Name: "evidence", err: errors.New(`ent: missing required edge "ClaimEvidence.evidence"`)}
	}
	return nil
}

func (_c *ClaimEvidenceCreate) sqlSave(ctx context.Context) (*ClaimEvidence, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClaimEvidenceCreate) createSpec() (*ClaimEvidence, *sqlgraph.CreateSpec) {
	var (
		_node = &ClaimEvidence{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(claimevidence.Table, sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(claimevidence.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(claimevidence.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(claimevidence.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ClaimIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.ClaimTable,
			Columns: []string{claimevidence.ClaimColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClaimID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EvidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claimevidence.EvidenceTable,
			Columns: []string{claimevidence.EvidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EvidenceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClaimEvidenceCreateBulk is the builder for creating many ClaimEvidence entities in bulk.
type ClaimEvidenceCreateBulk struct {
	config
	err      error
	builders []*ClaimEvidenceCreate
}

// Save creates the ClaimEvidence entities in the database.
func (_c *ClaimEvidenceCreateBulk) Save(ctx context.Context) ([]*ClaimEvidence, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClaimEvidence, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClaimEvidenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClaimEvidenceCreateBulk) SaveX(ctx context.Context) []*ClaimEvidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClaimEvidenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClaimEvidenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
