// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"api/ent/predicate"
	"api/ent/project"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ClaimQuery is the builder for querying Claim entities.
type ClaimQuery struct {
	config
	ctx                *QueryContext
	order              []claim.OrderOption
	inters             []Interceptor
	predicates         []predicate.Claim
	withProject        *ProjectQuery
	withEvidences      *EvidenceQuery
	withClaimEvidences *ClaimEvidenceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClaimQuery builder.
func (_q *ClaimQuery) Where(ps ...predicate.Claim) *ClaimQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ClaimQuery) Limit(limit int) *ClaimQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ClaimQuery) Offset(offset int) *ClaimQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ClaimQuery) Unique(unique bool) *ClaimQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ClaimQuery) Order(o ...claim.OrderOption) *ClaimQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *ClaimQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(claim.Table, claim.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, claim.ProjectTable, claim.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvidences chains the current query on the "evidences" edge.
func (_q *ClaimQuery) QueryEvidences() *EvidenceQuery {
	query := (&EvidenceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(claim.Table, claim.FieldID, selector),
			sqlgraph.To(evidence.Table, evidence.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, claim.EvidencesTable, claim.EvidencesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClaimEvidences chains the current query on the "claim_evidences" edge.
func (_q *ClaimQuery) QueryClaimEvidences() *ClaimEvidenceQuery {
	query := (&ClaimEvidenceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(claim.Table, claim.FieldID, selector),
			sqlgraph.To(claimevidence.Table, claimevidence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, claim.ClaimEvidencesTable, claim.ClaimEvidencesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Claim entity from the query.
// Returns a *NotFoundError when no Claim was found.
func (_q *ClaimQuery) First(ctx context.Context) (*Claim, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{claim.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ClaimQuery) FirstX(ctx context.Context) *Claim {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Claim ID from the query.
// Returns a *NotFoundError when no Claim ID was found.
func (_q *ClaimQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{claim.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ClaimQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Claim entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Claim entity is found.
// Returns a *NotFoundError when no Claim entities are found.
func (_q *ClaimQuery) Only(ctx context.Context) (*Claim, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{claim.Label}
	default:
		return nil, &NotSingularError{claim.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ClaimQuery) OnlyX(ctx context.Context) *Claim {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Claim ID in the query.
// Returns a *NotSingularError when more than one Claim ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ClaimQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{claim.Label}
	default:
		err = &NotSingularError{claim.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ClaimQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Claims.
func (_q *ClaimQuery) All(ctx context.Context) ([]*Claim, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Claim, *ClaimQuery]()
	return withInterceptors[[]*Claim](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ClaimQuery) AllX(ctx context.Context) []*Claim {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Claim IDs.
func (_q *ClaimQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(claim.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ClaimQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ClaimQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ClaimQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ClaimQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ClaimQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ClaimQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClaimQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ClaimQuery) Clone() *ClaimQuery {
	if _q == nil {
		return nil
	}
	return &ClaimQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]claim.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.Claim{}, _q.predicates...),
		withProject:        _q.withProject.Clone(),
		withEvidences:      _q.withEvidences.Clone(),
		withClaimEvidences: _q.withClaimEvidences.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ClaimQuery) WithProject(opts ...func(*ProjectQuery)) *ClaimQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithEvidences tells the query-builder to eager-load the nodes that are connected to
// the "evidences" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ClaimQuery) WithEvidences(opts ...func(*EvidenceQuery)) *ClaimQuery {
	query := (&EvidenceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvidences = query
	return _q
}

// WithClaimEvidences tells the query-builder to eager-load the nodes that are connected to
// the "claim_evidences" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ClaimQuery) WithClaimEvidences(opts ...func(*ClaimEvidenceQuery)) *ClaimQuery {
	query := (&ClaimEvidenceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClaimEvidences = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Claim.Query().
//		GroupBy(claim.FieldProjectID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ClaimQuery) GroupBy(field string, fields ...string) *ClaimGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClaimGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = claim.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//	}
//
//	client.Claim.Query().
//		Select(claim.FieldProjectID).
//		Scan(ctx, &v)
func (_q *ClaimQuery) Select(fields ...string) *ClaimSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ClaimSelect{ClaimQuery: _q}
	sbuild.label = claim.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClaimSelect configured with the given aggregations.
func (_q *ClaimQuery) Aggregate(fns ...AggregateFunc) *ClaimSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ClaimQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !claim.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ClaimQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Claim, error) {
	var (
		nodes       = []*Claim{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withProject != nil,
			_q.withEvidences != nil,
			_q.withClaimEvidences != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Claim).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Claim{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *Claim, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvidences; query != nil {
		if err := _q.loadEvidences(ctx, query, nodes,
			func(n *Claim) { n.Edges.Evidences = []*Evidence{} },
			func(n *Claim, e *Evidence) { n.Edges.Evidences = append(n.Edges.Evidences, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withClaimEvidences; query != nil {
		if err := _q.loadClaimEvidences(ctx, query, nodes,
			func(n *Claim) { n.Edges.ClaimEvidences = []*ClaimEvidence{} },
			func(n *Claim, e *ClaimEvidence) { n.Edges.ClaimEvidences = append(n.Edges.ClaimEvidences, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ClaimQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*Claim, init func(*Claim), assign func(*Claim, *Project)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Claim)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ClaimQuery) loadEvidences(ctx context.Context, query *EvidenceQuery, nodes []*Claim, init func(*Claim), assign func(*Claim, *Evidence)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Claim)
	nids := make(map[uuid.UUID]map[*Claim]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(claim.EvidencesTable)
		s.Join(joinT).On(s.C(evidence.FieldID), joinT.C(claim.EvidencesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(claim.EvidencesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(claim.EvidencesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Claim]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Evidence](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "evidences" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *ClaimQuery) loadClaimEvidences(ctx context.Context, query *ClaimEvidenceQuery, nodes []*Claim, init func(*Claim), assign func(*Claim, *ClaimEvidence)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Claim)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(claimevidence.FieldClaimID)
	}
	query.Where(predicate.ClaimEvidence(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(claim.ClaimEvidencesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ClaimID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "claim_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ClaimQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ClaimQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(claim.Table, claim.Columns, sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, claim.FieldID)
		for i := range fields {
			if fields[i] != claim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(claim.FieldProjectID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ClaimQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(claim.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = claim.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClaimGroupBy is the group-by builder for Claim entities.
type ClaimGroupBy struct {
	selector
	build *ClaimQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ClaimGroupBy) Aggregate(fns ...AggregateFunc) *ClaimGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ClaimGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClaimQuery, *ClaimGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ClaimGroupBy) sqlScan(ctx context.Context, root *ClaimQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClaimSelect is the builder for selecting fields of Claim entities.
type ClaimSelect struct {
	*ClaimQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ClaimSelect) Aggregate(fns ...AggregateFunc) *ClaimSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ClaimSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClaimQuery, *ClaimSelect](ctx, _s.ClaimQuery, _s, _s.inters, v)
}

func (_s *ClaimSelect) sqlScan(ctx context.Context, root *ClaimQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
