// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"api/ent/predicate"
	"api/ent/project"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ClaimUpdate is the builder for updating Claim entities.
type ClaimUpdate struct {
	config
	hooks    []Hook
	mutation *ClaimMutation
}

// Where appends a list predicates to the ClaimUpdate builder.
func (_u *ClaimUpdate) Where(ps ...predicate.Claim) *ClaimUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ClaimUpdate) SetProjectID(v uuid.UUID) *ClaimUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ClaimUpdate) SetNillableProjectID(v *uuid.UUID) *ClaimUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ClaimUpdate) SetTitle(v string) *ClaimUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ClaimUpdate) SetNillableTitle(v *string) *ClaimUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *ClaimUpdate) SetBody(v string) *ClaimUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ClaimUpdate) SetNillableBody(v *string) *ClaimUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *ClaimUpdate) ClearBody() *ClaimUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClaimUpdate) SetStatus(v string) *ClaimUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClaimUpdate) SetNillableStatus(v *string) *ClaimUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClaimUpdate) SetUpdatedAt(v time.Time) *ClaimUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ClaimUpdate) SetProject(v *Project) *ClaimUpdate {
	return _u.SetProjectID(v.ID)
}

// AddEvidenceIDs adds the "evidences" edge to the Evidence entity by IDs.
func (_u *ClaimUpdate) AddEvidenceIDs(ids ...uuid.UUID) *ClaimUpdate {
	_u.mutation.AddEvidenceIDs(ids...)
	return _u
}

// AddEvidences adds the "evidences" edges to the Evidence entity.
func (_u *ClaimUpdate) AddEvidences(v ...*Evidence) *ClaimUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvidenceIDs(ids...)
}

// AddClaimEvidenceIDs adds the "claim_evidences" edge to the ClaimEvidence entity by IDs.
func (_u *ClaimUpdate) AddClaimEvidenceIDs(ids ...uuid.UUID) *ClaimUpdate {
	_u.mutation.AddClaimEvidenceIDs(ids...)
	return _u
}

// AddClaimEvidences adds the "claim_evidences" edges to the ClaimEvidence entity.
func (_u *ClaimUpdate) AddClaimEvidences(v ...*ClaimEvidence) *ClaimUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimEvidenceIDs(ids...)
}

// Mutation returns the ClaimMutation object of the builder.
func (_u *ClaimUpdate) Mutation() *ClaimMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ClaimUpdate) ClearProject() *ClaimUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearEvidences clears all "evidences" edges to the Evidence entity.
func (_u *ClaimUpdate) ClearEvidences() *ClaimUpdate {
	_u.mutation.ClearEvidences()
	return _u
}

// RemoveEvidenceIDs removes the "evidences" edge to Evidence entities by IDs.
func (_u *ClaimUpdate) RemoveEvidenceIDs(ids ...uuid.UUID) *ClaimUpdate {
	_u.mutation.RemoveEvidenceIDs(ids...)
	return _u
}

// RemoveEvidences removes "evidences" edges to Evidence entities.
func (_u *ClaimUpdate) RemoveEvidences(v ...*Evidence) *ClaimUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvidenceIDs(ids...)
}

// ClearClaimEvidences clears all "claim_evidences" edges to the ClaimEvidence entity.
func (_u *ClaimUpdate) ClearClaimEvidences() *ClaimUpdate {
	_u.mutation.ClearClaimEvidences()
	return _u
}

// RemoveClaimEvidenceIDs removes the "claim_evidences" edge to ClaimEvidence entities by IDs.
func (_u *ClaimUpdate) RemoveClaimEvidenceIDs(ids ...uuid.UUID) *ClaimUpdate {
	_u.mutation.RemoveClaimEvidenceIDs(ids...)
	return _u
}

// RemoveClaimEvidences removes "claim_evidences" edges to ClaimEvidence entities.
func (_u *ClaimUpdate) RemoveClaimEvidences(v ...*ClaimEvidence) *ClaimUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimEvidenceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClaimUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClaimUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClaimUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClaimUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := claim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClaimUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Claim.project"`)
	}
	return nil
}

func (_u *ClaimUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(claim.Table, claim.Columns, sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(claim.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(claim.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(claim.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(claim.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(claim.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   claim.ProjectTable,
			Columns: []string{claim.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   claim.ProjectTable,
			Columns: []string{claim.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   claim.EvidencesTable,
			Columns: claim.EvidencesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvidencesIDs(); len(nodes) > 0 && !_u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   claim.EvidencesTable,
			Columns: claim.EvidencesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   claim.EvidencesTable,
			Columns: claim.EvidencesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   claim.ClaimEvidencesTable,
			Columns: []string{claim.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimEvidencesIDs(); len(nodes) > 0 && !_u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   claim.ClaimEvidencesTable,
			Columns: []string{claim.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimEvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   claim.ClaimEvidencesTable,
			Columns: []string{claim.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClaimUpdateOne is the builder for updating a single Claim entity.
type ClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClaimMutation
}

// SetProjectID sets the "project_id" field.
func (_u *ClaimUpdateOne) SetProjectID(v uuid.UUID) *ClaimUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ClaimUpdateOne) SetNillableProjectID(v *uuid.UUID) *ClaimUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ClaimUpdateOne) SetTitle(v string) *ClaimUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ClaimUpdateOne) SetNillableTitle(v *string) *ClaimUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *ClaimUpdateOne) SetBody(v string) *ClaimUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ClaimUpdateOne) SetNillableBody(v *string) *ClaimUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *ClaimUpdateOne) ClearBody() *ClaimUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClaimUpdateOne) SetStatus(v string) *ClaimUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClaimUpdateOne) SetNillableStatus(v *string) *ClaimUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClaimUpdateOne) SetUpdatedAt(v time.Time) *ClaimUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ClaimUpdateOne) SetProject(v *Project) *ClaimUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddEvidenceIDs adds the "evidences" edge to the Evidence entity by IDs.
func (_u *ClaimUpdateOne) AddEvidenceIDs(ids ...uuid.UUID) *ClaimUpdateOne {
	_u.mutation.AddEvidenceIDs(ids...)
	return _u
}

// AddEvidences adds the "evidences" edges to the Evidence entity.
func (_u *ClaimUpdateOne) AddEvidences(v ...*Evidence) *ClaimUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvidenceIDs(ids...)
}

// AddClaimEvidenceIDs adds the "claim_evidences" edge to the ClaimEvidence entity by IDs.
func (_u *ClaimUpdateOne) AddClaimEvidenceIDs(ids ...uuid.UUID) *ClaimUpdateOne {
	_u.mutation.AddClaimEvidenceIDs(ids...)
	return _u
}

// AddClaimEvidences adds the "claim_evidences" edges to the ClaimEvidence entity.
func (_u *ClaimUpdateOne) AddClaimEvidences(v ...*ClaimEvidence) *ClaimUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimEvidenceIDs(ids...)
}

// Mutation returns the ClaimMutation object of the builder.
func (_u *ClaimUpdateOne) Mutation() *ClaimMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ClaimUpdateOne) ClearProject() *ClaimUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearEvidences clears all "evidences" edges to the Evidence entity.
func (_u *ClaimUpdateOne) ClearEvidences() *ClaimUpdateOne {
	_u.mutation.ClearEvidences()
	return _u
}

// RemoveEvidenceIDs removes the "evidences" edge to Evidence entities by IDs.
func (_u *ClaimUpdateOne) RemoveEvidenceIDs(ids ...uuid.UUID) *ClaimUpdateOne {
	_u.mutation.RemoveEvidenceIDs(ids...)
	return _u
}

// RemoveEvidences removes "evidences" edges to Evidence entities.
func (_u *ClaimUpdateOne) RemoveEvidences(v ...*Evidence) *ClaimUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvidenceIDs(ids...)
}

// ClearClaimEvidences clears all "claim_evidences" edges to the ClaimEvidence entity.
func (_u *ClaimUpdateOne) ClearClaimEvidences() *ClaimUpdateOne {
	_u.mutation.ClearClaimEvidences()
	return _u
}

// RemoveClaimEvidenceIDs removes the "claim_evidences" edge to ClaimEvidence entities by IDs.
func (_u *ClaimUpdateOne) RemoveClaimEvidenceIDs(ids ...uuid.UUID) *ClaimUpdateOne {
	_u.mutation.RemoveClaimEvidenceIDs(ids...)
	return _u
}

// RemoveClaimEvidences removes "claim_evidences" edges to ClaimEvidence entities.
func (_u *ClaimUpdateOne) RemoveClaimEvidences(v ...*ClaimEvidence) *ClaimUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimEvidenceIDs(ids...)
}

// Where appends a list predicates to the ClaimUpdate builder.
func (_u *ClaimUpdateOne) Where(ps ...predicate.Claim) *ClaimUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClaimUpdateOne) Select(field string, fields ...string) *ClaimUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Claim entity.
func (_u *ClaimUpdateOne) Save(ctx context.Context) (*Claim, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClaimUpdateOne) SaveX(ctx context.Context) *Claim {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClaimUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClaimUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := claim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClaimUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Claim.project"`)
	}
	return nil
}

func (_u *ClaimUpdateOne) sqlSave(ctx context.Context) (_node *Claim, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(claim.Table, claim.Columns, sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Claim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, claim.FieldID)
		for _, f := range fields {
			if !claim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != claim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(claim.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(claim.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(claim.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(claim.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(claim.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   claim.ProjectTable,
			Columns: []string{claim.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   claim.ProjectTable,
			Columns: []string{claim.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   claim.EvidencesTable,
			Columns: claim.EvidencesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvidencesIDs(); len(nodes) > 0 && !_u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   claim.EvidencesTable,
			Columns: claim.EvidencesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   claim.EvidencesTable,
			Columns: claim.EvidencesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   claim.ClaimEvidencesTable,
			Columns: []string{claim.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimEvidencesIDs(); len(nodes) > 0 && !_u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   claim.ClaimEvidencesTable,
			Columns: []string{claim.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimEvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   claim.ClaimEvidencesTable,
			Columns: []string{claim.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Claim{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
