// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"api/ent/migrate"

	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"api/ent/project"
	"api/ent/source"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Claim is the client for interacting with the Claim builders.
	Claim *ClaimClient
	// ClaimEvidence is the client for interacting with the ClaimEvidence builders.
	ClaimEvidence *ClaimEvidenceClient
	// Evidence is the client for interacting with the Evidence builders.
	Evidence *EvidenceClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// Source is the client for interacting with the Source builders.
	Source *SourceClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Claim = NewClaimClient(c.config)
	c.ClaimEvidence = NewClaimEvidenceClient(c.config)
	c.Evidence = NewEvidenceClient(c.config)
	c.Project = NewProjectClient(c.config)
	c.Source = NewSourceClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Claim:         NewClaimClient(cfg),
		ClaimEvidence: NewClaimEvidenceClient(cfg),
		Evidence:      NewEvidenceClient(cfg),
		Project:       NewProjectClient(cfg),
		Source:        NewSourceClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Claim:         NewClaimClient(cfg),
		ClaimEvidence: NewClaimEvidenceClient(cfg),
		Evidence:      NewEvidenceClient(cfg),
		Project:       NewProjectClient(cfg),
		Source:        NewSourceClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Claim.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Claim.Use(hooks...)
	c.ClaimEvidence.Use(hooks...)
	c.Evidence.Use(hooks...)
	c.Project.Use(hooks...)
	c.Source.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Claim.Intercept(interceptors...)
	c.ClaimEvidence.Intercept(interceptors...)
	c.Evidence.Intercept(interceptors...)
	c.Project.Intercept(interceptors...)
	c.Source.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ClaimMutation:
		return c.Claim.mutate(ctx, m)
	case *ClaimEvidenceMutation:
		return c.ClaimEvidence.mutate(ctx, m)
	case *EvidenceMutation:
		return c.Evidence.mutate(ctx, m)
	case *ProjectMutation:
		return c.Project.mutate(ctx, m)
	case *SourceMutation:
		return c.Source.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ClaimClient is a client for the Claim schema.
type ClaimClient struct {
	config
}

// NewClaimClient returns a client for the Claim from the given config.
func NewClaimClient(c config) *ClaimClient {
	return &ClaimClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `claim.Hooks(f(g(h())))`.
func (c *ClaimClient) Use(hooks ...Hook) {
	c.hooks.Claim = append(c.hooks.Claim, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `claim.Intercept(f(g(h())))`.
func (c *ClaimClient) Intercept(interceptors ...Interceptor) {
	c.inters.Claim = append(c.inters.Claim, interceptors...)
}

// Create returns a builder for creating a Claim entity.
func (c *ClaimClient) Create() *ClaimCreate {
	mutation := newClaimMutation(c.config, OpCreate)
	return &ClaimCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Claim entities.
func (c *ClaimClient) CreateBulk(builders ...*ClaimCreate) *ClaimCreateBulk {
	return &ClaimCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ClaimClient) MapCreateBulk(slice any, setFunc func(*ClaimCreate, int)) *ClaimCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ClaimCreateBulk{err: fmt.Errorf("calling to ClaimClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ClaimCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ClaimCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Claim.
func (c *ClaimClient) Update() *ClaimUpdate {
	mutation := newClaimMutation(c.config, OpUpdate)
	return &ClaimUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ClaimClient) UpdateOne(_m *Claim) *ClaimUpdateOne {
	mutation := newClaimMutation(c.config, OpUpdateOne, withClaim(_m))
	return &ClaimUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ClaimClient) UpdateOneID(id uuid.UUID) *ClaimUpdateOne {
	mutation := newClaimMutation(c.config, OpUpdateOne, withClaimID(id))
	return &ClaimUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Claim.
func (c *ClaimClient) Delete() *ClaimDelete {
	mutation := newClaimMutation(c.config, OpDelete)
	return &ClaimDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ClaimClient) DeleteOne(_m *Claim) *ClaimDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ClaimClient) DeleteOneID(id uuid.UUID) *ClaimDeleteOne {
	builder := c.Delete().Where(claim.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ClaimDeleteOne{builder}
}

// Query returns a query builder for Claim.
func (c *ClaimClient) Query() *ClaimQuery {
	return &ClaimQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeClaim},
		inters: c.Interceptors(),
	}
}

// Get returns a Claim entity by its id.
func (c *ClaimClient) Get(ctx context.Context, id uuid.UUID) (*Claim, error) {
	return c.Query().Where(claim.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ClaimClient) GetX(ctx context.Context, id uuid.UUID) *Claim {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a Claim.
func (c *ClaimClient) QueryProject(_m *Claim) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(claim.Table, claim.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, claim.ProjectTable, claim.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvidences queries the evidences edge of a Claim.
func (c *ClaimClient) QueryEvidences(_m *Claim) *EvidenceQuery {
	query := (&EvidenceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(claim.Table, claim.FieldID, id),
			sqlgraph.To(evidence.Table, evidence.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, claim.EvidencesTable, claim.EvidencesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryClaimEvidences queries the claim_evidences edge of a Claim.
func (c *ClaimClient) QueryClaimEvidences(_m *Claim) *ClaimEvidenceQuery {
	query := (&ClaimEvidenceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(claim.Table, claim.FieldID, id),
			sqlgraph.To(claimevidence.Table, claimevidence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, claim.ClaimEvidencesTable, claim.ClaimEvidencesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ClaimClient) Hooks() []Hook {
	return c.hooks.Claim
}

// Interceptors returns the client interceptors.
func (c *ClaimClient) Interceptors() []Interceptor {
	return c.inters.Claim
}

func (c *ClaimClient) mutate(ctx context.Context, m *ClaimMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ClaimCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ClaimUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ClaimUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ClaimDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Claim mutation op: %q", m.Op())
	}
}

// ClaimEvidenceClient is a client for the ClaimEvidence schema.
type ClaimEvidenceClient struct {
	config
}

// NewClaimEvidenceClient returns a client for the ClaimEvidence from the given config.
func NewClaimEvidenceClient(c config) *ClaimEvidenceClient {
	return &ClaimEvidenceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `claimevidence.Hooks(f(g(h())))`.
func (c *ClaimEvidenceClient) Use(hooks ...Hook) {
	c.hooks.ClaimEvidence = append(c.hooks.ClaimEvidence, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `claimevidence.Intercept(f(g(h())))`.
func (c *ClaimEvidenceClient) Intercept(interceptors ...Interceptor) {
	c.inters.ClaimEvidence = append(c.inters.ClaimEvidence, interceptors...)
}

// Create returns a builder for creating a ClaimEvidence entity.
func (c *ClaimEvidenceClient) Create() *ClaimEvidenceCreate {
	mutation := newClaimEvidenceMutation(c.config, OpCreate)
	return &ClaimEvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ClaimEvidence entities.
func (c *ClaimEvidenceClient) CreateBulk(builders ...*ClaimEvidenceCreate) *ClaimEvidenceCreateBulk {
	return &ClaimEvidenceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ClaimEvidenceClient) MapCreateBulk(slice any, setFunc func(*ClaimEvidenceCreate, int)) *ClaimEvidenceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ClaimEvidenceCreateBulk{err: fmt.Errorf("calling to ClaimEvidenceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ClaimEvidenceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ClaimEvidenceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ClaimEvidence.
func (c *ClaimEvidenceClient) Update() *ClaimEvidenceUpdate {
	mutation := newClaimEvidenceMutation(c.config, OpUpdate)
	return &ClaimEvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ClaimEvidenceClient) UpdateOne(_m *ClaimEvidence) *ClaimEvidenceUpdateOne {
	mutation := newClaimEvidenceMutation(c.config, OpUpdateOne, withClaimEvidence(_m))
	return &ClaimEvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ClaimEvidenceClient) UpdateOneID(id uuid.UUID) *ClaimEvidenceUpdateOne {
	mutation := newClaimEvidenceMutation(c.config, OpUpdateOne, withClaimEvidenceID(id))
	return &ClaimEvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ClaimEvidence.
func (c *ClaimEvidenceClient) Delete() *ClaimEvidenceDelete {
	mutation := newClaimEvidenceMutation(c.config, OpDelete)
	return &ClaimEvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ClaimEvidenceClient) DeleteOne(_m *ClaimEvidence) *ClaimEvidenceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ClaimEvidenceClient) DeleteOneID(id uuid.UUID) *ClaimEvidenceDeleteOne {
	builder := c.Delete().Where(claimevidence.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ClaimEvidenceDeleteOne{builder}
}

// Query returns a query builder for ClaimEvidence.
func (c *ClaimEvidenceClient) Query() *ClaimEvidenceQuery {
	return &ClaimEvidenceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeClaimEvidence},
		inters: c.Interceptors(),
	}
}

// Get returns a ClaimEvidence entity by its id.
func (c *ClaimEvidenceClient) Get(ctx context.Context, id uuid.UUID) (*ClaimEvidence, error) {
	return c.Query().Where(claimevidence.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ClaimEvidenceClient) GetX(ctx context.Context, id uuid.UUID) *ClaimEvidence {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryClaim queries the claim edge of a ClaimEvidence.
func (c *ClaimEvidenceClient) QueryClaim(_m *ClaimEvidence) *ClaimQuery {
	query := (&ClaimClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(claimevidence.Table, claimevidence.FieldID, id),
			sqlgraph.To(claim.Table, claim.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, claimevidence.ClaimTable, claimevidence.ClaimColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvidence queries the evidence edge of a ClaimEvidence.
func (c *ClaimEvidenceClient) QueryEvidence(_m *ClaimEvidence) *EvidenceQuery {
	query := (&EvidenceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(claimevidence.Table, claimevidence.FieldID, id),
			sqlgraph.To(evidence.Table, evidence.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, claimevidence.EvidenceTable, claimevidence.EvidenceColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ClaimEvidenceClient) Hooks() []Hook {
	return c.hooks.ClaimEvidence
}

// Interceptors returns the client interceptors.
func (c *ClaimEvidenceClient) Interceptors() []Interceptor {
	return c.inters.ClaimEvidence
}

func (c *ClaimEvidenceClient) mutate(ctx context.Context, m *ClaimEvidenceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ClaimEvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ClaimEvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ClaimEvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ClaimEvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ClaimEvidence mutation op: %q", m.Op())
	}
}

// EvidenceClient is a client for the Evidence schema.
type EvidenceClient struct {
	config
}

// NewEvidenceClient returns a client for the Evidence from the given config.
func NewEvidenceClient(c config) *EvidenceClient {
	return &EvidenceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `evidence.Hooks(f(g(h())))`.
func (c *EvidenceClient) Use(hooks ...Hook) {
	c.hooks.Evidence = append(c.hooks.Evidence, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `evidence.Intercept(f(g(h())))`.
func (c *EvidenceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Evidence = append(c.inters.Evidence, interceptors...)
}

// Create returns a builder for creating a Evidence entity.
func (c *EvidenceClient) Create() *EvidenceCreate {
	mutation := newEvidenceMutation(c.config, OpCreate)
	return &EvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Evidence entities.
func (c *EvidenceClient) CreateBulk(builders ...*EvidenceCreate) *EvidenceCreateBulk {
	return &EvidenceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EvidenceClient) MapCreateBulk(slice any, setFunc func(*EvidenceCreate, int)) *EvidenceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EvidenceCreateBulk{err: fmt.Errorf("calling to EvidenceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EvidenceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EvidenceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Evidence.
func (c *EvidenceClient) Update() *EvidenceUpdate {
	mutation := newEvidenceMutation(c.config, OpUpdate)
	return &EvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EvidenceClient) UpdateOne(_m *Evidence) *EvidenceUpdateOne {
	mutation := newEvidenceMutation(c.config, OpUpdateOne, withEvidence(_m))
	return &EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EvidenceClient) UpdateOneID(id uuid.UUID) *EvidenceUpdateOne {
	mutation := newEvidenceMutation(c.config, OpUpdateOne, withEvidenceID(id))
	return &EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Evidence.
func (c *EvidenceClient) Delete() *EvidenceDelete {
	mutation := newEvidenceMutation(c.config, OpDelete)
	return &EvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EvidenceClient) DeleteOne(_m *Evidence) *EvidenceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EvidenceClient) DeleteOneID(id uuid.UUID) *EvidenceDeleteOne {
	builder := c.Delete().Where(evidence.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EvidenceDeleteOne{builder}
}

// Query returns a query builder for Evidence.
func (c *EvidenceClient) Query() *EvidenceQuery {
	return &EvidenceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEvidence},
		inters: c.Interceptors(),
	}
}

// Get returns a Evidence entity by its id.
func (c *EvidenceClient) Get(ctx context.Context, id uuid.UUID) (*Evidence, error) {
	return c.Query().Where(evidence.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EvidenceClient) GetX(ctx context.Context, id uuid.UUID) *Evidence {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a Evidence.
func (c *EvidenceClient) QueryProject(_m *Evidence) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(evidence.Table, evidence.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, evidence.ProjectTable, evidence.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySource queries the source edge of a Evidence.
func (c *EvidenceClient) QuerySource(_m *Evidence) *SourceQuery {
	query := (&SourceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(evidence.Table, evidence.FieldID, id),
			sqlgraph.To(source.Table, source.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, evidence.SourceTable, evidence.SourceColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryClaims queries the claims edge of a Evidence.
func (c *EvidenceClient) QueryClaims(_m *Evidence) *ClaimQuery {
	query := (&ClaimClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(evidence.Table, evidence.FieldID, id),
			sqlgraph.To(claim.Table, claim.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, evidence.ClaimsTable, evidence.ClaimsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryClaimEvidences queries the claim_evidences edge of a Evidence.
func (c *EvidenceClient) QueryClaimEvidences(_m *Evidence) *ClaimEvidenceQuery {
	query := (&ClaimEvidenceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(evidence.Table, evidence.FieldID, id),
			sqlgraph.To(claimevidence.Table, claimevidence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, evidence.ClaimEvidencesTable, evidence.ClaimEvidencesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EvidenceClient) Hooks() []Hook {
	return c.hooks.Evidence
}

// Interceptors returns the client interceptors.
func (c *EvidenceClient) Interceptors() []Interceptor {
	return c.inters.Evidence
}

func (c *EvidenceClient) mutate(ctx context.Context, m *EvidenceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EvidenceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EvidenceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EvidenceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EvidenceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Evidence mutation op: %q", m.Op())
	}
}

// ProjectClient is a client for the Project schema.
type ProjectClient struct {
	config
}

// NewProjectClient returns a client for the Project from the given config.
func NewProjectClient(c config) *ProjectClient {
	return &ProjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `project.Hooks(f(g(h())))`.
func (c *ProjectClient) Use(hooks ...Hook) {
	c.hooks.Project = append(c.hooks.Project, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `project.Intercept(f(g(h())))`.
func (c *ProjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.Project = append(c.inters.Project, interceptors...)
}

// Create returns a builder for creating a Project entity.
func (c *ProjectClient) Create() *ProjectCreate {
	mutation := newProjectMutation(c.config, OpCreate)
	return &ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Project entities.
func (c *ProjectClient) CreateBulk(builders ...*ProjectCreate) *ProjectCreateBulk {
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectClient) MapCreateBulk(slice any, setFunc func(*ProjectCreate, int)) *ProjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectCreateBulk{err: fmt.Errorf("calling to ProjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Project.
func (c *ProjectClient) Update() *ProjectUpdate {
	mutation := newProjectMutation(c.config, OpUpdate)
	return &ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectClient) UpdateOne(_m *Project) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProject(_m))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectClient) UpdateOneID(id uuid.UUID) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProjectID(id))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Project.
func (c *ProjectClient) Delete() *ProjectDelete {
	mutation := newProjectMutation(c.config, OpDelete)
	return &ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectClient) DeleteOne(_m *Project) *ProjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectClient) DeleteOneID(id uuid.UUID) *ProjectDeleteOne {
	builder := c.Delete().Where(project.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectDeleteOne{builder}
}

// Query returns a query builder for Project.
func (c *ProjectClient) Query() *ProjectQuery {
	return &ProjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProject},
		inters: c.Interceptors(),
	}
}

// Get returns a Project entity by its id.
func (c *ProjectClient) Get(ctx context.Context, id uuid.UUID) (*Project, error) {
	return c.Query().Where(project.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectClient) GetX(ctx context.Context, id uuid.UUID) *Project {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryClaims queries the claims edge of a Project.
func (c *ProjectClient) QueryClaims(_m *Project) *ClaimQuery {
	query := (&ClaimClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(claim.Table, claim.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, project.ClaimsTable, project.ClaimsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvidences queries the evidences edge of a Project.
func (c *ProjectClient) QueryEvidences(_m *Project) *EvidenceQuery {
	query := (&EvidenceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(evidence.Table, evidence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, project.EvidencesTable, project.EvidencesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProjectClient) Hooks() []Hook {
	return c.hooks.Project
}

// Interceptors returns the client interceptors.
func (c *ProjectClient) Interceptors() []Interceptor {
	return c.inters.Project
}

func (c *ProjectClient) mutate(ctx context.Context, m *ProjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Project mutation op: %q", m.Op())
	}
}

// SourceClient is a client for the Source schema.
type SourceClient struct {
	config
}

// NewSourceClient returns a client for the Source from the given config.
func NewSourceClient(c config) *SourceClient {
	return &SourceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `source.Hooks(f(g(h())))`.
func (c *SourceClient) Use(hooks ...Hook) {
	c.hooks.Source = append(c.hooks.Source, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `source.Intercept(f(g(h())))`.
func (c *SourceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Source = append(c.inters.Source, interceptors...)
}

// Create returns a builder for creating a Source entity.
func (c *SourceClient) Create() *SourceCreate {
	mutation := newSourceMutation(c.config, OpCreate)
	return &SourceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Source entities.
func (c *SourceClient) CreateBulk(builders ...*SourceCreate) *SourceCreateBulk {
	return &SourceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SourceClient) MapCreateBulk(slice any, setFunc func(*SourceCreate, int)) *SourceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SourceCreateBulk{err: fmt.Errorf("calling to SourceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SourceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SourceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Source.
func (c *SourceClient) Update() *SourceUpdate {
	mutation := newSourceMutation(c.config, OpUpdate)
	return &SourceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SourceClient) UpdateOne(_m *Source) *SourceUpdateOne {
	mutation := newSourceMutation(c.config, OpUpdateOne, withSource(_m))
	return &SourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SourceClient) UpdateOneID(id uuid.UUID) *SourceUpdateOne {
	mutation := newSourceMutation(c.config, OpUpdateOne, withSourceID(id))
	return &SourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Source.
func (c *SourceClient) Delete() *SourceDelete {
	mutation := newSourceMutation(c.config, OpDelete)
	return &SourceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SourceClient) DeleteOne(_m *Source) *SourceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SourceClient) DeleteOneID(id uuid.UUID) *SourceDeleteOne {
	builder := c.Delete().Where(source.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SourceDeleteOne{builder}
}

// Query returns a query builder for Source.
func (c *SourceClient) Query() *SourceQuery {
	return &SourceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSource},
		inters: c.Interceptors(),
	}
}

// Get returns a Source entity by its id.
func (c *SourceClient) Get(ctx context.Context, id uuid.UUID) (*Source, error) {
	return c.Query().Where(source.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SourceClient) GetX(ctx context.Context, id uuid.UUID) *Source {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEvidences queries the evidences edge of a Source.
func (c *SourceClient) QueryEvidences(_m *Source) *EvidenceQuery {
	query := (&EvidenceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(source.Table, source.FieldID, id),
			sqlgraph.To(evidence.Table, evidence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, source.EvidencesTable, source.EvidencesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SourceClient) Hooks() []Hook {
	return c.hooks.Source
}

// Interceptors returns the client interceptors.
func (c *SourceClient) Interceptors() []Interceptor {
	return c.inters.Source
}

func (c *SourceClient) mutate(ctx context.Context, m *SourceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SourceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SourceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SourceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Source mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Claim, ClaimEvidence, Evidence, Project, Source []ent.Hook
	}
	inters struct {
		Claim, ClaimEvidence, Evidence, Project, Source []ent.Interceptor
	}
)
