// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"api/ent/predicate"
	"api/ent/project"
	"api/ent/source"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EvidenceUpdate is the builder for updating Evidence entities.
type EvidenceUpdate struct {
	config
	hooks    []Hook
	mutation *EvidenceMutation
}

// Where appends a list predicates to the EvidenceUpdate builder.
func (_u *EvidenceUpdate) Where(ps ...predicate.Evidence) *EvidenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EvidenceUpdate) SetProjectID(v uuid.UUID) *EvidenceUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableProjectID(v *uuid.UUID) *EvidenceUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *EvidenceUpdate) SetSourceID(v uuid.UUID) *EvidenceUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableSourceID(v *uuid.UUID) *EvidenceUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetQuote sets the "quote" field.
func (_u *EvidenceUpdate) SetQuote(v string) *EvidenceUpdate {
	_u.mutation.SetQuote(v)
	return _u
}

// SetNillableQuote sets the "quote" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableQuote(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetQuote(*v)
	}
	return _u
}

// ClearQuote clears the value of the "quote" field.
func (_u *EvidenceUpdate) ClearQuote() *EvidenceUpdate {
	_u.mutation.ClearQuote()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *EvidenceUpdate) SetSummary(v string) *EvidenceUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableSummary(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *EvidenceUpdate) ClearSummary() *EvidenceUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetLocator sets the "locator" field.
func (_u *EvidenceUpdate) SetLocator(v string) *EvidenceUpdate {
	_u.mutation.SetLocator(v)
	return _u
}

// SetNillableLocator sets the "locator" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableLocator(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetLocator(*v)
	}
	return _u
}

// ClearLocator clears the value of the "locator" field.
func (_u *EvidenceUpdate) ClearLocator() *EvidenceUpdate {
	_u.mutation.ClearLocator()
	return _u
}

// SetNote sets the "note" field.
func (_u *EvidenceUpdate) SetNote(v string) *EvidenceUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *EvidenceUpdate) SetNillableNote(v *string) *EvidenceUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *EvidenceUpdate) ClearNote() *EvidenceUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvidenceUpdate) SetUpdatedAt(v time.Time) *EvidenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EvidenceUpdate) SetProject(v *Project) *EvidenceUpdate {
	return _u.SetProjectID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_u *EvidenceUpdate) SetSource(v *Source) *EvidenceUpdate {
	return _u.SetSourceID(v.ID)
}

// AddClaimIDs adds the "claims" edge to the Claim entity by IDs.
func (_u *EvidenceUpdate) AddClaimIDs(ids ...uuid.UUID) *EvidenceUpdate {
	_u.mutation.AddClaimIDs(ids...)
	return _u
}

// AddClaims adds the "claims" edges to the Claim entity.
func (_u *EvidenceUpdate) AddClaims(v ...*Claim) *EvidenceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimIDs(ids...)
}

// AddClaimEvidenceIDs adds the "claim_evidences" edge to the ClaimEvidence entity by IDs.
func (_u *EvidenceUpdate) AddClaimEvidenceIDs(ids ...uuid.UUID) *EvidenceUpdate {
	_u.mutation.AddClaimEvidenceIDs(ids...)
	return _u
}

// AddClaimEvidences adds the "claim_evidences" edges to the ClaimEvidence entity.
func (_u *EvidenceUpdate) AddClaimEvidences(v ...*ClaimEvidence) *EvidenceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimEvidenceIDs(ids...)
}

// Mutation returns the EvidenceMutation object of the builder.
func (_u *EvidenceUpdate) Mutation() *EvidenceMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EvidenceUpdate) ClearProject() *EvidenceUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *EvidenceUpdate) ClearSource() *EvidenceUpdate {
	_u.mutation.ClearSource()
	return _u
}

// ClearClaims clears all "claims" edges to the Claim entity.
func (_u *EvidenceUpdate) ClearClaims() *EvidenceUpdate {
	_u.mutation.ClearClaims()
	return _u
}

// RemoveClaimIDs removes the "claims" edge to Claim entities by IDs.
func (_u *EvidenceUpdate) RemoveClaimIDs(ids ...uuid.UUID) *EvidenceUpdate {
	_u.mutation.RemoveClaimIDs(ids...)
	return _u
}

// RemoveClaims removes "claims" edges to Claim entities.
func (_u *EvidenceUpdate) RemoveClaims(v ...*Claim) *EvidenceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimIDs(ids...)
}

// ClearClaimEvidences clears all "claim_evidences" edges to the ClaimEvidence entity.
func (_u *EvidenceUpdate) ClearClaimEvidences() *EvidenceUpdate {
	_u.mutation.ClearClaimEvidences()
	return _u
}

// RemoveClaimEvidenceIDs removes the "claim_evidences" edge to ClaimEvidence entities by IDs.
func (_u *EvidenceUpdate) RemoveClaimEvidenceIDs(ids ...uuid.UUID) *EvidenceUpdate {
	_u.mutation.RemoveClaimEvidenceIDs(ids...)
	return _u
}

// RemoveClaimEvidences removes "claim_evidences" edges to ClaimEvidence entities.
func (_u *EvidenceUpdate) RemoveClaimEvidences(v ...*ClaimEvidence) *EvidenceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimEvidenceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvidenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvidenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvidenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvidenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvidenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evidence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvidenceUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Evidence.project"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Evidence.source"`)
	}
	return nil
}

func (_u *EvidenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evidence.Table, evidence.Columns, sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quote(); ok {
		_spec.SetField(evidence.FieldQuote, field.TypeString, value)
	}
	if _u.mutation.QuoteCleared() {
		_spec.ClearField(evidence.FieldQuote, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(evidence.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(evidence.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Locator(); ok {
		_spec.SetField(evidence.FieldLocator, field.TypeString, value)
	}
	if _u.mutation.LocatorCleared() {
		_spec.ClearField(evidence.FieldLocator, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(evidence.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(evidence.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evidence.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.ProjectTable,
			Columns: []string{evidence.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.ProjectTable,
			Columns: []string{evidence.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.SourceTable,
			Columns: []string{evidence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.SourceTable,
			Columns: []string{evidence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   evidence.ClaimsTable,
			Columns: evidence.ClaimsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimsIDs(); len(nodes) > 0 && !_u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   evidence.ClaimsTable,
			Columns: evidence.ClaimsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   evidence.ClaimsTable,
			Columns: evidence.ClaimsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   evidence.ClaimEvidencesTable,
			Columns: []string{evidence.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimEvidencesIDs(); len(nodes) > 0 && !_u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   evidence.ClaimEvidencesTable,
			Columns: []string{evidence.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimEvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   evidence.ClaimEvidencesTable,
			Columns: []string{evidence.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvidenceUpdateOne is the builder for updating a single Evidence entity.
type EvidenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvidenceMutation
}

// SetProjectID sets the "project_id" field.
func (_u *EvidenceUpdateOne) SetProjectID(v uuid.UUID) *EvidenceUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableProjectID(v *uuid.UUID) *EvidenceUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *EvidenceUpdateOne) SetSourceID(v uuid.UUID) *EvidenceUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableSourceID(v *uuid.UUID) *EvidenceUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetQuote sets the "quote" field.
func (_u *EvidenceUpdateOne) SetQuote(v string) *EvidenceUpdateOne {
	_u.mutation.SetQuote(v)
	return _u
}

// SetNillableQuote sets the "quote" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableQuote(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetQuote(*v)
	}
	return _u
}

// ClearQuote clears the value of the "quote" field.
func (_u *EvidenceUpdateOne) ClearQuote() *EvidenceUpdateOne {
	_u.mutation.ClearQuote()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *EvidenceUpdateOne) SetSummary(v string) *EvidenceUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableSummary(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *EvidenceUpdateOne) ClearSummary() *EvidenceUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetLocator sets the "locator" field.
func (_u *EvidenceUpdateOne) SetLocator(v string) *EvidenceUpdateOne {
	_u.mutation.SetLocator(v)
	return _u
}

// SetNillableLocator sets the "locator" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableLocator(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetLocator(*v)
	}
	return _u
}

// ClearLocator clears the value of the "locator" field.
func (_u *EvidenceUpdateOne) ClearLocator() *EvidenceUpdateOne {
	_u.mutation.ClearLocator()
	return _u
}

// SetNote sets the "note" field.
func (_u *EvidenceUpdateOne) SetNote(v string) *EvidenceUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *EvidenceUpdateOne) SetNillableNote(v *string) *EvidenceUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *EvidenceUpdateOne) ClearNote() *EvidenceUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvidenceUpdateOne) SetUpdatedAt(v time.Time) *EvidenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EvidenceUpdateOne) SetProject(v *Project) *EvidenceUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_u *EvidenceUpdateOne) SetSource(v *Source) *EvidenceUpdateOne {
	return _u.SetSourceID(v.ID)
}

// AddClaimIDs adds the "claims" edge to the Claim entity by IDs.
func (_u *EvidenceUpdateOne) AddClaimIDs(ids ...uuid.UUID) *EvidenceUpdateOne {
	_u.mutation.AddClaimIDs(ids...)
	return _u
}

// AddClaims adds the "claims" edges to the Claim entity.
func (_u *EvidenceUpdateOne) AddClaims(v ...*Claim) *EvidenceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimIDs(ids...)
}

// AddClaimEvidenceIDs adds the "claim_evidences" edge to the ClaimEvidence entity by IDs.
func (_u *EvidenceUpdateOne) AddClaimEvidenceIDs(ids ...uuid.UUID) *EvidenceUpdateOne {
	_u.mutation.AddClaimEvidenceIDs(ids...)
	return _u
}

// AddClaimEvidences adds the "claim_evidences" edges to the ClaimEvidence entity.
func (_u *EvidenceUpdateOne) AddClaimEvidences(v ...*ClaimEvidence) *EvidenceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimEvidenceIDs(ids...)
}

// Mutation returns the EvidenceMutation object of the builder.
func (_u *EvidenceUpdateOne) Mutation() *EvidenceMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EvidenceUpdateOne) ClearProject() *EvidenceUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *EvidenceUpdateOne) ClearSource() *EvidenceUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// ClearClaims clears all "claims" edges to the Claim entity.
func (_u *EvidenceUpdateOne) ClearClaims() *EvidenceUpdateOne {
	_u.mutation.ClearClaims()
	return _u
}

// RemoveClaimIDs removes the "claims" edge to Claim entities by IDs.
func (_u *EvidenceUpdateOne) RemoveClaimIDs(ids ...uuid.UUID) *EvidenceUpdateOne {
	_u.mutation.RemoveClaimIDs(ids...)
	return _u
}

// RemoveClaims removes "claims" edges to Claim entities.
func (_u *EvidenceUpdateOne) RemoveClaims(v ...*Claim) *EvidenceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimIDs(ids...)
}

// ClearClaimEvidences clears all "claim_evidences" edges to the ClaimEvidence entity.
func (_u *EvidenceUpdateOne) ClearClaimEvidences() *EvidenceUpdateOne {
	_u.mutation.ClearClaimEvidences()
	return _u
}

// RemoveClaimEvidenceIDs removes the "claim_evidences" edge to ClaimEvidence entities by IDs.
func (_u *EvidenceUpdateOne) RemoveClaimEvidenceIDs(ids ...uuid.UUID) *EvidenceUpdateOne {
	_u.mutation.RemoveClaimEvidenceIDs(ids...)
	return _u
}

// RemoveClaimEvidences removes "claim_evidences" edges to ClaimEvidence entities.
func (_u *EvidenceUpdateOne) RemoveClaimEvidences(v ...*ClaimEvidence) *EvidenceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimEvidenceIDs(ids...)
}

// Where appends a list predicates to the EvidenceUpdate builder.
func (_u *EvidenceUpdateOne) Where(ps ...predicate.Evidence) *EvidenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvidenceUpdateOne) Select(field string, fields ...string) *EvidenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Evidence entity.
func (_u *EvidenceUpdateOne) Save(ctx context.Context) (*Evidence, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvidenceUpdateOne) SaveX(ctx context.Context) *Evidence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvidenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvidenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvidenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evidence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvidenceUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Evidence.project"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Evidence.source"`)
	}
	return nil
}

func (_u *EvidenceUpdateOne) sqlSave(ctx context.Context) (_node *Evidence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evidence.Table, evidence.Columns, sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Evidence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evidence.FieldID)
		for _, f := range fields {
			if !evidence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != evidence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quote(); ok {
		_spec.SetField(evidence.FieldQuote, field.TypeString, value)
	}
	if _u.mutation.QuoteCleared() {
		_spec.ClearField(evidence.FieldQuote, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(evidence.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(evidence.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Locator(); ok {
		_spec.SetField(evidence.FieldLocator, field.TypeString, value)
	}
	if _u.mutation.LocatorCleared() {
		_spec.ClearField(evidence.FieldLocator, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(evidence.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(evidence.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evidence.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.ProjectTable,
			Columns: []string{evidence.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.ProjectTable,
			Columns: []string{evidence.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.SourceTable,
			Columns: []string{evidence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.SourceTable,
			Columns: []string{evidence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   evidence.ClaimsTable,
			Columns: evidence.ClaimsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimsIDs(); len(nodes) > 0 && !_u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   evidence.ClaimsTable,
			Columns: evidence.ClaimsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   evidence.ClaimsTable,
			Columns: evidence.ClaimsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _u.config, mutation: newClaimEvidenceMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   evidence.ClaimEvidencesTable,
			Columns: []string{evidence.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimEvidencesIDs(); len(nodes) > 0 && !_u.mutation.ClaimEvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   evidence.ClaimEvidencesTable,
			Columns: []string{evidence.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimEvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   evidence.ClaimEvidencesTable,
			Columns: []string{evidence.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Evidence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evidence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
