// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/evidence"
	"api/ent/project"
	"api/ent/source"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Evidence is the model entity for the Evidence schema.
type Evidence struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID uuid.UUID `json:"source_id,omitempty"`
	// Quote holds the value of the "quote" field.
	Quote *string `json:"quote,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary *string `json:"summary,omitempty"`
	// Locator holds the value of the "locator" field.
	Locator *string `json:"locator,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EvidenceQuery when eager-loading is set.
	Edges        EvidenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EvidenceEdges holds the relations/edges for other nodes in the graph.
type EvidenceEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Source holds the value of the source edge.
	Source *Source `json:"source,omitempty"`
	// Claims holds the value of the claims edge.
	Claims []*Claim `json:"claims,omitempty"`
	// ClaimEvidences holds the value of the claim_evidences edge.
	ClaimEvidences []*ClaimEvidence `json:"claim_evidences,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EvidenceEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EvidenceEdges) SourceOrErr() (*Source, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: source.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// ClaimsOrErr returns the Claims value or an error if the edge
// was not loaded in eager-loading.
func (e EvidenceEdges) ClaimsOrErr() ([]*Claim, error) {
	if e.loadedTypes[2] {
		return e.Claims, nil
	}
	return nil, &NotLoadedError{edge: "claims"}
}

// ClaimEvidencesOrErr returns the ClaimEvidences value or an error if the edge
// was not loaded in eager-loading.
func (e EvidenceEdges) ClaimEvidencesOrErr() ([]*ClaimEvidence, error) {
	if e.loadedTypes[3] {
		return e.ClaimEvidences, nil
	}
	return nil, &NotLoadedError{edge: "claim_evidences"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Evidence) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case evidence.FieldQuote, evidence.FieldSummary, evidence.FieldLocator, evidence.FieldNote:
			values[i] = new(sql.NullString)
		case evidence.FieldCreatedAt, evidence.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case evidence.FieldID, evidence.FieldProjectID, evidence.FieldSourceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Evidence fields.
func (_m *Evidence) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case evidence.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case evidence.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case evidence.FieldSourceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value != nil {
				_m.SourceID = *value
			}
		case evidence.FieldQuote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quote", values[i])
			} else if value.Valid {
				_m.Quote = new(string)
				*_m.Quote = value.String
			}
		case evidence.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = new(string)
				*_m.Summary = value.String
			}
		case evidence.FieldLocator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locator", values[i])
			} else if value.Valid {
				_m.Locator = new(string)
				*_m.Locator = value.String
			}
		case evidence.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case evidence.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case evidence.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Evidence.
// This includes values selected through modifiers, order, etc.
func (_m *Evidence) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Evidence entity.
func (_m *Evidence) QueryProject() *ProjectQuery {
	return NewEvidenceClient(_m.config).QueryProject(_m)
}

// QuerySource queries the "source" edge of the Evidence entity.
func (_m *Evidence) QuerySource() *SourceQuery {
	return NewEvidenceClient(_m.config).QuerySource(_m)
}

// QueryClaims queries the "claims" edge of the Evidence entity.
func (_m *Evidence) QueryClaims() *ClaimQuery {
	return NewEvidenceClient(_m.config).QueryClaims(_m)
}

// QueryClaimEvidences queries the "claim_evidences" edge of the Evidence entity.
func (_m *Evidence) QueryClaimEvidences() *ClaimEvidenceQuery {
	return NewEvidenceClient(_m.config).QueryClaimEvidences(_m)
}

// Update returns a builder for updating this Evidence.
// Note that you need to call Evidence.Unwrap() before calling this method if this Evidence
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Evidence) Update() *EvidenceUpdateOne {
	return NewEvidenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Evidence entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Evidence) Unwrap() *Evidence {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Evidence is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Evidence) String() string {
	var builder strings.Builder
	builder.WriteString("Evidence(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	if v := _m.Quote; v != nil {
		builder.WriteString("quote=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Summary; v != nil {
		builder.WriteString("summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Locator; v != nil {
		builder.WriteString("locator=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Evidences is a parsable slice of Evidence.
type Evidences []*Evidence
