// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"api/ent/project"
	"api/ent/source"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EvidenceCreate is the builder for creating a Evidence entity.
type EvidenceCreate struct {
	config
	mutation *EvidenceMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *EvidenceCreate) SetProjectID(v uuid.UUID) *EvidenceCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *EvidenceCreate) SetSourceID(v uuid.UUID) *EvidenceCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetQuote sets the "quote" field.
func (_c *EvidenceCreate) SetQuote(v string) *EvidenceCreate {
	_c.mutation.SetQuote(v)
	return _c
}

// SetNillableQuote sets the "quote" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableQuote(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetQuote(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *EvidenceCreate) SetSummary(v string) *EvidenceCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableSummary(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetLocator sets the "locator" field.
func (_c *EvidenceCreate) SetLocator(v string) *EvidenceCreate {
	_c.mutation.SetLocator(v)
	return _c
}

// SetNillableLocator sets the "locator" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableLocator(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetLocator(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *EvidenceCreate) SetNote(v string) *EvidenceCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableNote(v *string) *EvidenceCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EvidenceCreate) SetCreatedAt(v time.Time) *EvidenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableCreatedAt(v *time.Time) *EvidenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EvidenceCreate) SetUpdatedAt(v time.Time) *EvidenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableUpdatedAt(v *time.Time) *EvidenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EvidenceCreate) SetID(v uuid.UUID) *EvidenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EvidenceCreate) SetNillableID(v *uuid.UUID) *EvidenceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *EvidenceCreate) SetProject(v *Project) *EvidenceCreate {
	return _c.SetProjectID(v.ID)
}

// SetSource sets the "source" edge to the Source entity.
func (_c *EvidenceCreate) SetSource(v *Source) *EvidenceCreate {
	return _c.SetSourceID(v.ID)
}

// AddClaimIDs adds the "claims" edge to the Claim entity by IDs.
func (_c *EvidenceCreate) AddClaimIDs(ids ...uuid.UUID) *EvidenceCreate {
	_c.mutation.AddClaimIDs(ids...)
	return _c
}

// AddClaims adds the "claims" edges to the Claim entity.
func (_c *EvidenceCreate) AddClaims(v ...*Claim) *EvidenceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClaimIDs(ids...)
}

// AddClaimEvidenceIDs adds the "claim_evidences" edge to the ClaimEvidence entity by IDs.
func (_c *EvidenceCreate) AddClaimEvidenceIDs(ids ...uuid.UUID) *EvidenceCreate {
	_c.mutation.AddClaimEvidenceIDs(ids...)
	return _c
}

// AddClaimEvidences adds the "claim_evidences" edges to the ClaimEvidence entity.
func (_c *EvidenceCreate) AddClaimEvidences(v ...*ClaimEvidence) *EvidenceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClaimEvidenceIDs(ids...)
}

// Mutation returns the EvidenceMutation object of the builder.
func (_c *EvidenceCreate) Mutation() *EvidenceMutation {
	return _c.mutation
}

// Save creates the Evidence in the database.
func (_c *EvidenceCreate) Save(ctx context.Context) (*Evidence, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EvidenceCreate) SaveX(ctx context.Context) *Evidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvidenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvidenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EvidenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := evidence.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := evidence.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := evidence.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EvidenceCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Evidence.project_id"`)}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "Evidence.source_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Evidence.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Evidence.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Evidence.project"`)}
	}
	if len(_c.mutation.SourceIDs()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required edge "Evidence.source"`)}
	}
	return nil
}

func (_c *EvidenceCreate) sqlSave(ctx context.Context) (*Evidence, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EvidenceCreate) createSpec() (*Evidence, *sqlgraph.CreateSpec) {
	var (
		_node = &Evidence{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(evidence.Table, sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Quote(); ok {
		_spec.SetField(evidence.FieldQuote, field.TypeString, value)
		_node.Quote = &value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(evidence.FieldSummary, field.TypeString, value)
		_node.Summary = &value
	}
	if value, ok := _c.mutation.Locator(); ok {
		_spec.SetField(evidence.FieldLocator, field.TypeString, value)
		_node.Locator = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(evidence.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(evidence.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(evidence.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.ProjectTable,
			Columns: []string{evidence.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evidence.SourceTable,
			Columns: []string{evidence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   evidence.ClaimsTable,
			Columns: evidence.ClaimsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claim.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClaimEvidenceCreate{config: _c.config, mutation: newClaimEvidenceMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClaimEvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   evidence.ClaimEvidencesTable,
			Columns: []string{evidence.ClaimEvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(claimevidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EvidenceCreateBulk is the builder for creating many Evidence entities in bulk.
type EvidenceCreateBulk struct {
	config
	err      error
	builders []*EvidenceCreate
}

// Save creates the Evidence entities in the database.
func (_c *EvidenceCreateBulk) Save(ctx context.Context) ([]*Evidence, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Evidence, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EvidenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EvidenceCreateBulk) SaveX(ctx context.Context) []*Evidence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EvidenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EvidenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
