// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/claim"
	"api/ent/claimevidence"
	"api/ent/evidence"
	"api/ent/project"
	"api/ent/schema"
	"api/ent/source"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	claimFields := schema.Claim{}.Fields()
	_ = claimFields
	// claimDescStatus is the schema descriptor for status field.
	claimDescStatus := claimFields[4].Descriptor()
	// claim.DefaultStatus holds the default value on creation for the status field.
	claim.DefaultStatus = claimDescStatus.Default.(string)
	// claimDescCreatedAt is the schema descriptor for created_at field.
	claimDescCreatedAt := claimFields[5].Descriptor()
	// claim.DefaultCreatedAt holds the default value on creation for the created_at field.
	claim.DefaultCreatedAt = claimDescCreatedAt.Default.(func() time.Time)
	// claimDescUpdatedAt is the schema descriptor for updated_at field.
	claimDescUpdatedAt := claimFields[6].Descriptor()
	// claim.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	claim.DefaultUpdatedAt = claimDescUpdatedAt.Default.(func() time.Time)
	// claim.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	claim.UpdateDefaultUpdatedAt = claimDescUpdatedAt.UpdateDefault.(func() time.Time)
	// claimDescID is the schema descriptor for id field.
	claimDescID := claimFields[0].Descriptor()
	// claim.DefaultID holds the default value on creation for the id field.
	claim.DefaultID = claimDescID.Default.(func() uuid.UUID)
	claimevidenceFields := schema.ClaimEvidence{}.Fields()
	_ = claimevidenceFields
	// claimevidenceDescCreatedAt is the schema descriptor for created_at field.
	claimevidenceDescCreatedAt := claimevidenceFields[5].Descriptor()
	// claimevidence.DefaultCreatedAt holds the default value on creation for the created_at field.
	claimevidence.DefaultCreatedAt = claimevidenceDescCreatedAt.Default.(func() time.Time)
	// claimevidenceDescID is the schema descriptor for id field.
	claimevidenceDescID := claimevidenceFields[0].Descriptor()
	// claimevidence.DefaultID holds the default value on creation for the id field.
	claimevidence.DefaultID = claimevidenceDescID.Default.(func() uuid.UUID)
	evidenceFields := schema.Evidence{}.Fields()
	_ = evidenceFields
	// evidenceDescCreatedAt is the schema descriptor for created_at field.
	evidenceDescCreatedAt := evidenceFields[7].Descriptor()
	// evidence.DefaultCreatedAt holds the default value on creation for the created_at field.
	evidence.DefaultCreatedAt = evidenceDescCreatedAt.Default.(func() time.Time)
	// evidenceDescUpdatedAt is the schema descriptor for updated_at field.
	evidenceDescUpdatedAt := evidenceFields[8].Descriptor()
	// evidence.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	evidence.DefaultUpdatedAt = evidenceDescUpdatedAt.Default.(func() time.Time)
	// evidence.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	evidence.UpdateDefaultUpdatedAt = evidenceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// evidenceDescID is the schema descriptor for id field.
	evidenceDescID := evidenceFields[0].Descriptor()
	// evidence.DefaultID holds the default value on creation for the id field.
	evidence.DefaultID = evidenceDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[3].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[4].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	sourceFields := schema.Source{}.Fields()
	_ = sourceFields
	// sourceDescCreatedAt is the schema descriptor for created_at field.
	sourceDescCreatedAt := sourceFields[6].Descriptor()
	// source.DefaultCreatedAt holds the default value on creation for the created_at field.
	source.DefaultCreatedAt = sourceDescCreatedAt.Default.(func() time.Time)
	// sourceDescUpdatedAt is the schema descriptor for updated_at field.
	sourceDescUpdatedAt := sourceFields[7].Descriptor()
	// source.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	source.DefaultUpdatedAt = sourceDescUpdatedAt.Default.(func() time.Time)
	// source.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	source.UpdateDefaultUpdatedAt = sourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sourceDescID is the schema descriptor for id field.
	sourceDescID := sourceFields[0].Descriptor()
	// source.DefaultID holds the default value on creation for the id field.
	source.DefaultID = sourceDescID.Default.(func() uuid.UUID)
}
