// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/evidence"
	"api/ent/predicate"
	"api/ent/source"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SourceUpdate is the builder for updating Source entities.
type SourceUpdate struct {
	config
	hooks    []Hook
	mutation *SourceMutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdate) Where(ps ...predicate.Source) *SourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *SourceUpdate) SetTitle(v string) *SourceUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableTitle(v *string) *SourceUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SourceUpdate) SetType(v string) *SourceUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableType(v *string) *SourceUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *SourceUpdate) ClearType() *SourceUpdate {
	_u.mutation.ClearType()
	return _u
}

// SetYear sets the "year" field.
func (_u *SourceUpdate) SetYear(v int) *SourceUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableYear(v *int) *SourceUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *SourceUpdate) AddYear(v int) *SourceUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *SourceUpdate) ClearYear() *SourceUpdate {
	_u.mutation.ClearYear()
	return _u
}

// SetURL sets the "url" field.
func (_u *SourceUpdate) SetURL(v string) *SourceUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableURL(v *string) *SourceUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *SourceUpdate) ClearURL() *SourceUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SourceUpdate) SetMetadata(v map[string]interface{}) *SourceUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SourceUpdate) ClearMetadata() *SourceUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdate) SetUpdatedAt(v time.Time) *SourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEvidenceIDs adds the "evidences" edge to the Evidence entity by IDs.
func (_u *SourceUpdate) AddEvidenceIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.AddEvidenceIDs(ids...)
	return _u
}

// AddEvidences adds the "evidences" edges to the Evidence entity.
func (_u *SourceUpdate) AddEvidences(v ...*Evidence) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvidenceIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdate) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearEvidences clears all "evidences" edges to the Evidence entity.
func (_u *SourceUpdate) ClearEvidences() *SourceUpdate {
	_u.mutation.ClearEvidences()
	return _u
}

// RemoveEvidenceIDs removes the "evidences" edge to Evidence entities by IDs.
func (_u *SourceUpdate) RemoveEvidenceIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.RemoveEvidenceIDs(ids...)
	return _u
}

// RemoveEvidences removes "evidences" edges to Evidence entities.
func (_u *SourceUpdate) RemoveEvidences(v ...*Evidence) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvidenceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(source.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(source.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(source.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(source.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(source.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(source.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(source.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(source.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(source.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(source.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.EvidencesTable,
			Columns: []string{source.EvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvidencesIDs(); len(nodes) > 0 && !_u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.EvidencesTable,
			Columns: []string{source.EvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.EvidencesTable,
			Columns: []string{source.EvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceUpdateOne is the builder for updating a single Source entity.
type SourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceMutation
}

// SetTitle sets the "title" field.
func (_u *SourceUpdateOne) SetTitle(v string) *SourceUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableTitle(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SourceUpdateOne) SetType(v string) *SourceUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableType(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *SourceUpdateOne) ClearType() *SourceUpdateOne {
	_u.mutation.ClearType()
	return _u
}

// SetYear sets the "year" field.
func (_u *SourceUpdateOne) SetYear(v int) *SourceUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableYear(v *int) *SourceUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *SourceUpdateOne) AddYear(v int) *SourceUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *SourceUpdateOne) ClearYear() *SourceUpdateOne {
	_u.mutation.ClearYear()
	return _u
}

// SetURL sets the "url" field.
func (_u *SourceUpdateOne) SetURL(v string) *SourceUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableURL(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *SourceUpdateOne) ClearURL() *SourceUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SourceUpdateOne) SetMetadata(v map[string]interface{}) *SourceUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SourceUpdateOne) ClearMetadata() *SourceUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdateOne) SetUpdatedAt(v time.Time) *SourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEvidenceIDs adds the "evidences" edge to the Evidence entity by IDs.
func (_u *SourceUpdateOne) AddEvidenceIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.AddEvidenceIDs(ids...)
	return _u
}

// AddEvidences adds the "evidences" edges to the Evidence entity.
func (_u *SourceUpdateOne) AddEvidences(v ...*Evidence) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvidenceIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdateOne) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearEvidences clears all "evidences" edges to the Evidence entity.
func (_u *SourceUpdateOne) ClearEvidences() *SourceUpdateOne {
	_u.mutation.ClearEvidences()
	return _u
}

// RemoveEvidenceIDs removes the "evidences" edge to Evidence entities by IDs.
func (_u *SourceUpdateOne) RemoveEvidenceIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.RemoveEvidenceIDs(ids...)
	return _u
}

// RemoveEvidences removes "evidences" edges to Evidence entities.
func (_u *SourceUpdateOne) RemoveEvidences(v ...*Evidence) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvidenceIDs(ids...)
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdateOne) Where(ps ...predicate.Source) *SourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceUpdateOne) Select(field string, fields ...string) *SourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Source entity.
func (_u *SourceUpdateOne) Save(ctx context.Context) (*Source, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdateOne) SaveX(ctx context.Context) *Source {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SourceUpdateOne) sqlSave(ctx context.Context) (_node *Source, err error) {
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Source.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, source.FieldID)
		for _, f := range fields {
			if !source.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != source.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(source.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(source.FieldType, field.TypeString, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(source.FieldType, field.TypeString)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(source.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(source.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(source.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(source.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(source.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(source.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(source.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.EvidencesTable,
			Columns: []string{source.EvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvidencesIDs(); len(nodes) > 0 && !_u.mutation.EvidencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.EvidencesTable,
			Columns: []string{source.EvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.EvidencesTable,
			Columns: []string{source.EvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Source{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
