// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/evidence"
	"api/ent/source"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SourceCreate is the builder for creating a Source entity.
type SourceCreate struct {
	config
	mutation *SourceMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *SourceCreate) SetTitle(v string) *SourceCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetType sets the "type" field.
func (_c *SourceCreate) SetType(v string) *SourceCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *SourceCreate) SetNillableType(v *string) *SourceCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetYear sets the "year" field.
func (_c *SourceCreate) SetYear(v int) *SourceCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_c *SourceCreate) SetNillableYear(v *int) *SourceCreate {
	if v != nil {
		_c.SetYear(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *SourceCreate) SetURL(v string) *SourceCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *SourceCreate) SetNillableURL(v *string) *SourceCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SourceCreate) SetMetadata(v map[string]interface{}) *SourceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SourceCreate) SetCreatedAt(v time.Time) *SourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableCreatedAt(v *time.Time) *SourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SourceCreate) SetUpdatedAt(v time.Time) *SourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SourceCreate) SetNillableUpdatedAt(v *time.Time) *SourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SourceCreate) SetID(v uuid.UUID) *SourceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SourceCreate) SetNillableID(v *uuid.UUID) *SourceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddEvidenceIDs adds the "evidences" edge to the Evidence entity by IDs.
func (_c *SourceCreate) AddEvidenceIDs(ids ...uuid.UUID) *SourceCreate {
	_c.mutation.AddEvidenceIDs(ids...)
	return _c
}

// AddEvidences adds the "evidences" edges to the Evidence entity.
func (_c *SourceCreate) AddEvidences(v ...*Evidence) *SourceCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEvidenceIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_c *SourceCreate) Mutation() *SourceMutation {
	return _c.mutation
}

// Save creates the Source in the database.
func (_c *SourceCreate) Save(ctx context.Context) (*Source, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceCreate) SaveX(ctx context.Context) *Source {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SourceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := source.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := source.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := source.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Source.title"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Source.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Source.updated_at"`)}
	}
	return nil
}

func (_c *SourceCreate) sqlSave(ctx context.Context) (*Source, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceCreate) createSpec() (*Source, *sqlgraph.CreateSpec) {
	var (
		_node = &Source{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(source.Table, sqlgraph.NewFieldSpec(source.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(source.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(source.FieldType, field.TypeString, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(source.FieldYear, field.TypeInt, value)
		_node.Year = &value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(source.FieldURL, field.TypeString, value)
		_node.URL = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(source.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(source.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.EvidencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.EvidencesTable,
			Columns: []string{source.EvidencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SourceCreateBulk is the builder for creating many Source entities in bulk.
type SourceCreateBulk struct {
	config
	err      error
	builders []*SourceCreate
}

// Save creates the Source entities in the database.
func (_c *SourceCreateBulk) Save(ctx context.Context) ([]*Source, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Source, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceCreateBulk) SaveX(ctx context.Context) []*Source {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
