// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClaimsColumns holds the columns for the "claims" table.
	ClaimsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeString, Size: 2147483647, Default: "active"},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "project_id", Type: field.TypeUUID},
	}
	// ClaimsTable holds the schema information for the "claims" table.
	ClaimsTable = &schema.Table{
		Name:       "claims",
		Columns:    ClaimsColumns,
		PrimaryKey: []*schema.Column{ClaimsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "claims_projects_claims",
				Columns:    []*schema.Column{ClaimsColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "claim_project_id",
				Unique:  false,
				Columns: []*schema.Column{ClaimsColumns[6]},
			},
		},
	}
	// ClaimEvidencesColumns holds the columns for the "claim_evidences" table.
	ClaimEvidencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeString, Size: 2147483647},
		{Name: "note", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "claim_id", Type: field.TypeUUID},
		{Name: "evidence_id", Type: field.TypeUUID},
	}
	// ClaimEvidencesTable holds the schema information for the "claim_evidences" table.
	ClaimEvidencesTable = &schema.Table{
		Name:       "claim_evidences",
		Columns:    ClaimEvidencesColumns,
		PrimaryKey: []*schema.Column{ClaimEvidencesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "claim_evidences_claims_claim",
				Columns:    []*schema.Column{ClaimEvidencesColumns[4]},
				RefColumns: []*schema.Column{ClaimsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "claim_evidences_evidences_evidence",
				Columns:    []*schema.Column{ClaimEvidencesColumns[5]},
				RefColumns: []*schema.Column{EvidencesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "claimevidence_claim_id_evidence_id_type",
				Unique:  true,
				Columns: []*schema.Column{ClaimEvidencesColumns[4], ClaimEvidencesColumns[5], ClaimEvidencesColumns[1]},
			},
			{
				Name:    "claimevidence_evidence_id",
				Unique:  false,
				Columns: []*schema.Column{ClaimEvidencesColumns[5]},
			},
		},
	}
	// EvidencesColumns holds the columns for the "evidences" table.
	EvidencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "quote", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "locator", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "note", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "source_id", Type: field.TypeUUID},
	}
	// EvidencesTable holds the schema information for the "evidences" table.
	EvidencesTable = &schema.Table{
		Name:       "evidences",
		Columns:    EvidencesColumns,
		PrimaryKey: []*schema.Column{EvidencesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "evidences_projects_evidences",
				Columns:    []*schema.Column{EvidencesColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "evidences_sources_evidences",
				Columns:    []*schema.Column{EvidencesColumns[8]},
				RefColumns: []*schema.Column{SourcesColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "evidence_project_id",
				Unique:  false,
				Columns: []*schema.Column{EvidencesColumns[7]},
			},
			{
				Name:    "evidence_source_id",
				Unique:  false,
				Columns: []*schema.Column{EvidencesColumns[8]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// SourcesColumns holds the columns for the "sources" table.
	SourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "type", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "year", Type: field.TypeInt, Nullable: true, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// SourcesTable holds the schema information for the "sources" table.
	SourcesTable = &schema.Table{
		Name:       "sources",
		Columns:    SourcesColumns,
		PrimaryKey: []*schema.Column{SourcesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClaimsTable,
		ClaimEvidencesTable,
		EvidencesTable,
		ProjectsTable,
		SourcesTable,
	}
)

func init() {
	ClaimsTable.ForeignKeys[0].RefTable = ProjectsTable
	ClaimsTable.Annotation = &entsql.Annotation{
		Table: "claims",
	}
	ClaimEvidencesTable.ForeignKeys[0].RefTable = ClaimsTable
	ClaimEvidencesTable.ForeignKeys[1].RefTable = EvidencesTable
	ClaimEvidencesTable.Annotation = &entsql.Annotation{
		Table: "claim_evidences",
	}
	EvidencesTable.ForeignKeys[0].RefTable = ProjectsTable
	EvidencesTable.ForeignKeys[1].RefTable = SourcesTable
	EvidencesTable.Annotation = &entsql.Annotation{
		Table: "evidences",
	}
	ProjectsTable.Annotation = &entsql.Annotation{
		Table: "projects",
	}
	SourcesTable.Annotation = &entsql.Annotation{
		Table: "sources",
	}
}
