// Code generated by ent, DO NOT EDIT.

package evidence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the evidence type in the database.
	Label = "evidence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldQuote holds the string denoting the quote field in the database.
	FieldQuote = "quote"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldLocator holds the string denoting the locator field in the database.
	FieldLocator = "locator"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeSource holds the string denoting the source edge name in mutations.
	EdgeSource = "source"
	// EdgeClaims holds the string denoting the claims edge name in mutations.
	EdgeClaims = "claims"
	// EdgeClaimEvidences holds the string denoting the claim_evidences edge name in mutations.
	EdgeClaimEvidences = "claim_evidences"
	// Table holds the table name of the evidence in the database.
	Table = "evidences"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "evidences"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// SourceTable is the table that holds the source relation/edge.
	SourceTable = "evidences"
	// SourceInverseTable is the table name for the Source entity.
	// It exists in this package in order to avoid circular dependency with the "source" package.
	SourceInverseTable = "sources"
	// SourceColumn is the table column denoting the source relation/edge.
	SourceColumn = "source_id"
	// ClaimsTable is the table that holds the claims relation/edge. The primary key declared below.
	ClaimsTable = "claim_evidences"
	// ClaimsInverseTable is the table name for the Claim entity.
	// It exists in this package in order to avoid circular dependency with the "claim" package.
	ClaimsInverseTable = "claims"
	// ClaimEvidencesTable is the table that holds the claim_evidences relation/edge.
	ClaimEvidencesTable = "claim_evidences"
	// ClaimEvidencesInverseTable is the table name for the ClaimEvidence entity.
	// It exists in this package in order to avoid circular dependency with the "claimevidence" package.
	ClaimEvidencesInverseTable = "claim_evidences"
	// ClaimEvidencesColumn is the table column denoting the claim_evidences relation/edge.
	ClaimEvidencesColumn = "evidence_id"
)

// Columns holds all SQL columns for evidence fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldSourceID,
	FieldQuote,
	FieldSummary,
	FieldLocator,
	FieldNote,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// ClaimsPrimaryKey and ClaimsColumn2 are the table columns denoting the
	// primary key for the claims relation (M2M).
	ClaimsPrimaryKey = []string{"claim_id", "evidence_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Evidence queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByQuote orders the results by the quote field.
func ByQuote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuote, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByLocator orders the results by the locator field.
func ByLocator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocator, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceField orders the results by source field.
func BySourceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceStep(), sql.OrderByField(field, opts...))
	}
}

// ByClaimsCount orders the results by claims count.
func ByClaimsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClaimsStep(), opts...)
	}
}

// ByClaims orders the results by claims terms.
func ByClaims(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClaimsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByClaimEvidencesCount orders the results by claim_evidences count.
func ByClaimEvidencesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClaimEvidencesStep(), opts...)
	}
}

// ByClaimEvidences orders the results by claim_evidences terms.
func ByClaimEvidences(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClaimEvidencesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newSourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
	)
}
func newClaimsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClaimsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ClaimsTable, ClaimsPrimaryKey...),
	)
}
func newClaimEvidencesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClaimEvidencesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ClaimEvidencesTable, ClaimEvidencesColumn),
	)
}
