// Code generated by ent, DO NOT EDIT.

package evidence

import (
	"api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldProjectID, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldSourceID, v))
}

// Quote applies equality check predicate on the "quote" field. It's identical to QuoteEQ.
func Quote(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldQuote, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldSummary, v))
}

// Locator applies equality check predicate on the "locator" field. It's identical to LocatorEQ.
func Locator(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldLocator, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldProjectID, vs...))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...uuid.UUID) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldSourceID, vs...))
}

// QuoteEQ applies the EQ predicate on the "quote" field.
func QuoteEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldQuote, v))
}

// QuoteNEQ applies the NEQ predicate on the "quote" field.
func QuoteNEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldQuote, v))
}

// QuoteIn applies the In predicate on the "quote" field.
func QuoteIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldQuote, vs...))
}

// QuoteNotIn applies the NotIn predicate on the "quote" field.
func QuoteNotIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldQuote, vs...))
}

// QuoteGT applies the GT predicate on the "quote" field.
func QuoteGT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGT(FieldQuote, v))
}

// QuoteGTE applies the GTE predicate on the "quote" field.
func QuoteGTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGTE(FieldQuote, v))
}

// QuoteLT applies the LT predicate on the "quote" field.
func QuoteLT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLT(FieldQuote, v))
}

// QuoteLTE applies the LTE predicate on the "quote" field.
func QuoteLTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLTE(FieldQuote, v))
}

// QuoteContains applies the Contains predicate on the "quote" field.
func QuoteContains(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContains(FieldQuote, v))
}

// QuoteHasPrefix applies the HasPrefix predicate on the "quote" field.
func QuoteHasPrefix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasPrefix(FieldQuote, v))
}

// QuoteHasSuffix applies the HasSuffix predicate on the "quote" field.
func QuoteHasSuffix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasSuffix(FieldQuote, v))
}

// QuoteIsNil applies the IsNil predicate on the "quote" field.
func QuoteIsNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldIsNull(FieldQuote))
}

// QuoteNotNil applies the NotNil predicate on the "quote" field.
func QuoteNotNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldNotNull(FieldQuote))
}

// QuoteEqualFold applies the EqualFold predicate on the "quote" field.
func QuoteEqualFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEqualFold(FieldQuote, v))
}

// QuoteContainsFold applies the ContainsFold predicate on the "quote" field.
func QuoteContainsFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContainsFold(FieldQuote, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContainsFold(FieldSummary, v))
}

// LocatorEQ applies the EQ predicate on the "locator" field.
func LocatorEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldLocator, v))
}

// LocatorNEQ applies the NEQ predicate on the "locator" field.
func LocatorNEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldLocator, v))
}

// LocatorIn applies the In predicate on the "locator" field.
func LocatorIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldLocator, vs...))
}

// LocatorNotIn applies the NotIn predicate on the "locator" field.
func LocatorNotIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldLocator, vs...))
}

// LocatorGT applies the GT predicate on the "locator" field.
func LocatorGT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGT(FieldLocator, v))
}

// LocatorGTE applies the GTE predicate on the "locator" field.
func LocatorGTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGTE(FieldLocator, v))
}

// LocatorLT applies the LT predicate on the "locator" field.
func LocatorLT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLT(FieldLocator, v))
}

// LocatorLTE applies the LTE predicate on the "locator" field.
func LocatorLTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLTE(FieldLocator, v))
}

// LocatorContains applies the Contains predicate on the "locator" field.
func LocatorContains(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContains(FieldLocator, v))
}

// LocatorHasPrefix applies the HasPrefix predicate on the "locator" field.
func LocatorHasPrefix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasPrefix(FieldLocator, v))
}

// LocatorHasSuffix applies the HasSuffix predicate on the "locator" field.
func LocatorHasSuffix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasSuffix(FieldLocator, v))
}

// LocatorIsNil applies the IsNil predicate on the "locator" field.
func LocatorIsNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldIsNull(FieldLocator))
}

// LocatorNotNil applies the NotNil predicate on the "locator" field.
func LocatorNotNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldNotNull(FieldLocator))
}

// LocatorEqualFold applies the EqualFold predicate on the "locator" field.
func LocatorEqualFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEqualFold(FieldLocator, v))
}

// LocatorContainsFold applies the ContainsFold predicate on the "locator" field.
func LocatorContainsFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContainsFold(FieldLocator, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Evidence {
	return predicate.Evidence(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Evidence {
	return predicate.Evidence(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Evidence {
	return predicate.Evidence(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.Source) predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClaims applies the HasEdge predicate on the "claims" edge.
func HasClaims() predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ClaimsTable, ClaimsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClaimsWith applies the HasEdge predicate on the "claims" edge with a given conditions (other predicates).
func HasClaimsWith(preds ...predicate.Claim) predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := newClaimsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClaimEvidences applies the HasEdge predicate on the "claim_evidences" edge.
func HasClaimEvidences() predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ClaimEvidencesTable, ClaimEvidencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClaimEvidencesWith applies the HasEdge predicate on the "claim_evidences" edge with a given conditions (other predicates).
func HasClaimEvidencesWith(preds ...predicate.ClaimEvidence) predicate.Evidence {
	return predicate.Evidence(func(s *sql.Selector) {
		step := newClaimEvidencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Evidence) predicate.Evidence {
	return predicate.Evidence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Evidence) predicate.Evidence {
	return predicate.Evidence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Evidence) predicate.Evidence {
	return predicate.Evidence(sql.NotPredicates(p))
}
